= jGoslin Parser, Validator and Normalized for Shorthand Lipid Nomenclatures
Nils Hoffmann <nils.hoffmann@isas.de>
:toc: macro

//image:https://travis-ci.org/lifs-tools/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/lifs-tools/jmzTab-m"] image:https://img.shields.io/maven-central/v/de.isas.lipidomics/jgoslin-cli.svg["Maven Central", link="https://search.maven.org/search?q=a:jgoslin-cli"] image:https://img.shields.io/github/release/lifs-tools/jmzTab-m.svg["Latest Release", link="https://github.com/lifs-tools/jmzTab-m/releases/latest"] image:https://zenodo.org/badge/107954666.svg["DOI", link="https://zenodo.org/badge/latestdoi/107954666"] image:https://img.shields.io/docker/pulls/lifs/jgoslin-cli.svg["Docker Hub Pulls", link="https://hub.docker.com/r/lifs/jgoslin-cli"] image:https://anaconda.org/bioconda/jgoslin-m/badges/installer/conda.svg["Install with Conda", link="https://anaconda.org/bioconda/jgoslin-m"]

//NOTE: If you use the jGoslin library or the web application, please cite the following paper: +
//https://pubs.acs.org/doi/10.1021/acs.analchem.9b01987[N. Hoffmann et al., Analytical Chemistry 2019; Oct 15;91(20):12615-12618..] https://www.ncbi.nlm.nih.gov/pubmed/31525911[PubMed record].


This project is a parser, validator and normalizer implementation for shorthand lipid nomenclatures, base on the https://github.com/lifs-tools/goslin[Grammar of Succinct Lipid Nomenclatures project].

Goslin defines multiple grammers compatible with https://www.antlr.org/[ANTLRv4] for different sources of shorthand lipid nomenclature. This allows to generate parsers based on the defined grammars,
which provide immediate feedback whether a processed lipid shorthand notation string is compliant with a particular grammar, or not.

jGoslin uses the Goslin grammars and the generateg parser to support the following general tasks:

. Facilitate the parsing of shorthand lipid names dialects.
. Provide a structural representation of the shorthand lipid after parsing.
. Use the structural representation to generate normalized names.

The Maven site with JavaDoc is available https://lifs-tools.github.io/jgoslin[here].

The web-based application is available https://github.com/lifs-tools/goslin-webapp[here].

toc::[]

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the necessary domain specific code for a number of different languages, e.g. for Python, JAVA and R.
In general, any language and framework for which swagger-codegen has templates available may be used. For details, please
look at the `api/pom.xml` file and at the https://github.com/swagger-api/swagger-codegen[swagger-codegen repository and documentation].

The generated code is available in the zip archives below the `api/target` directory:

. goslin-api-python https://github.com/lifs-tools/pymzTab-m[GitHub project]
. goslin-api-r https://github.com/lifs-tools/rmzTab-m[GitHub project]

The generated JAVA code is available in a jar archive below the `api/target` directory:

. jgoslin-api-<VERSION>.jar

The generated client libraries only contain the basic domain object code. Parsing from mzTab and writing to mzTab still need to be
implemented separately. The library provides this functionality for JAVA in the `io` sub-project.

== Running a validation with the command-line interface
The `cli` sub-project provides a command line interface for validation of files using the mzTab 2.0 draft validator.

NOTE: Currently, we do not plan to provide a CLI-based validator for mzTab 1.0, since that is still being provided by the original https://github.com/PRIDE-Utilities/jmzTab[jmzTab project].

After building the project as mentioned above with `./mvnw install`, the `cli/target` folder will contain the `cli-<version>-jgoslin-deployment.zip` file. Alternatively, you can download the latest
cli zip file from Maven central: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22de.isas.lipidomics%22%20AND%20a%3A%22jgoslin-cli%22%20[Search for latest cli artefact] and click on "bin.zip" to download.

In order to run the validator, unzip that file, change into the unzipped folder and run

  java -jar jgoslin-cli-<VERSION>.jar

to see the available options.

To validate a particular file with a given level (one of: Info, Warn, Error, where Info includes Warn and Error), run

  java -jar jgoslin-cli-<VERSION>.jar -c examples/MTBLS263.goslin -level Info

To run a semantic validation based on a controlled vocabulary term mapping file, run

  java -jar jgoslin-cli-<VERSION>.jar -c examples/MTBLS263.goslin -level Info -s cv-mapping/mzTab-M-mapping.xml

== Running the Web Application for Validation

The validator web application code has been moved into a separate project: https://github.com/lifs-tools/goslin-webapp
The application is available at: https://apps.lifs.isas.de/goslin

== Building the Docker Image

In order to build a Docker image of the command line interface application, run 

  ./mvnw -Pdocker install

from your commandline (mvnw.bat on Windows).
This will build and tag a Docker image lifs/jgoslin-cli with a corresponding version and make it available to your local Docker installation.
To show the coordinates of the image, call

  docker image ls | grep "jgoslin-cli"

== Pulling the latest Docker Image

The latest Docker image is now hosted at docker hub. To retrieve the latest version, run:

  docker pull lifs/jgoslin-cli

== Running the Docker Image

If you have not done so, please build the Docker image of the validator cli or pull it from the docker hub (see previous sections).
Then, run the following command, replacing `<VERSION>` with the current version, e.g. `1.0.4`) and `<DATA_DIR>` with the **local** directory containing your mzTab-M files:

  docker run -v <YOUR_DATA_DIR>:/home/data:rw lifs/jgoslin-cli:<VERSION>

This will only invoke the default entrypoint of the container, which is a shell script wrapper calling the jgoslin-m-cli Jar. It passes all arguments to the validator, so that all
arguments that you would pass normally will work in the same way (please replace `<YOUR_MZTABM_FILE>` with the actual file's name in `<YOUR_DATA_DIR>`:

  docker run -v <YOUR_DATA_DIR>:/home/data:rw lifs/jgoslin-cli:<VERSION> -c <YOUR_MZTABM_FILE>

== Using the project code releases via Maven Central

The library release artifacts are available from Maven Central.
If you want to use them, add the following lines to your own Maven pom file :

To use the IO libraries (reading, writing and structural and logical validation) in your own Maven projects, use the following dependency:

  <dependency>
    <groupId>de.isas.lipidomics</groupId>
    <artifactId>jgoslin-parsers</artifactId>
    <version>${jgoslin.version}</version>
  </dependency>

where `jgoslin.version` is the version of jgoslin you wish to use, e.g. for a release version:

  <properties>
    <jgoslin.version>1.0.4</jgoslin.version>
  </properties>

as defined in the properties section of your pom file.

== Using development snapshots

The library development artifacts are available as SNAPSHOT (development versions) from Sonatype's OSSRH repository.
If you want to use them, add the following lines to your own Maven pom file:

  <repositories>
    <repository>
      <name>Sonatype Snapshot Repository</name>
      <id>oss-sonatype-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
   ...
  </repositories>

The project coordinates for the api module are

    <dependency>
      <groupId>de.isas.lipidomics</groupId>
      <artifactId>jgoslin-api</artifactId>
      <version>${jgoslin.version}</version>
      <type>jar</type>
    </dependency>

and

    <dependency>
      <groupId>de.isas.lipidomics</groupId>
      <artifactId>jgoslin-io</artifactId>
      <version>${jgoslin.version}</version>
      <type>jar</type>
    </dependency>

for the io module, where `jgoslin.version` is the version of jgoslin you wish to use, e.g. for a `SNAPSHOT` version:

  <properties>
    <jgoslin.version>1.0.5-SNAPSHOT</jgoslin.version>
  </properties>

as defined in the properties section of your pom file.

The SNAPSHOTS are also available from https://oss.sonatype.org/content/repositories/snapshots/de.isas.lipidomics/.

== Using the API programmatically

=== Reading a Shorthand Lipid Name with a given Parser

The following snippet will parse a shorthand lipid name with the SwissLipidsParser:

  import uk.ac.ebi.pride.jgoslin2.*;
  import uk.ac.ebi.pride.jgoslin2.utils.*;
  import uk.ac.ebi.pride.jgoslin2.utils.errors.*;
  import de.isas.lipidomics.io.*;
  import de.isas.lipidomics.model.*;
  ...
  File mzTabFile = new File("/path/to/my/file.goslin");
  MzTabFileParser parser = new MzTabFileParser(mzTabFile);
  //will report a maxmimum of 500 errors on Error, Warn and Info levels
  //will output errors to System.err (onto your terminal)
  parser.parse(System.err, MZTabErrorType.Level.Info, 500);
  //inspect the output of the parse and errors
  MZTabErrorList errors = parser.getErrorList();
  //converting the MZTabErrorList into a list of ValidationMessage
  List<ValidationMessage> messages = errors.toValidationMessages()
  //access the file after parsing
  MzTab mzTab = parser.getMZTabFile();

=== Accessing the structural representation with a visitor parser

The mzTab domain model uses a _builder_ pattern, but also conforms to the usual JAVA _bean style_ pattern. The _builder_ pattern allows for a more fluent definition of your object structure. However, especially for cross references with the file, you will need to define e.g. MsRun objects separately since inline referencing within the builder code will not work.

The following code will create the first parts of an mzTab-M file programmatically:

  import de.isas.lipidomics.model.*;
  ...
  MzTab goslin = new MzTab();
  Metadata mtd = new Metadata();
  mtd.mzTabVersion("2.0.0-M");
  mtd.mzTabID("1");
  mtd.addSoftwareItem(new Software().id(1).
      parameter(new Parameter().id(1).
          name("LipidDataAnalyzer").
          value("2.6.3_nightly")));
  MsRun msrun1 = new MsRun().id(1).
      location(
          "file://D:/Experiment1/Orbitrap_CID/negative/50/014_Ex1_Orbitrap_CID_neg_50.chrom");
  mtd.addMsRunItem(msrun1);
  Assay a1 = new Assay().id(1).
      addMsRunRefItem(msrun1);
  Assay a2 = new Assay().id(2).
      addMsRunRefItem(msrun2);
  mtd.addAssayItem(a1).addAssayItem(a2);
  ...

== Exploring the test suite

The use-cases that were described in the previous sections are also covered in the unit tests. Particularly, the following classes are of interest:

* https://github.com/lifs-tools/jmzTab-m/blob/master/api/src/test/java/de.isas.lipidomics/model/MzTabTest.java[MzTabTest] - creation and serialization of MzTab object trees using the Jackson JSON serializer.
* https://github.com/lifs-tools/jmzTab-m/blob/master/io/src/test/java/de.isas.lipidomics/io/MZTabFileParserTest.java[MZTabFileParserTest] - test for reading of mzTab-m files.
* https://github.com/lifs-tools/jmzTab-m/blob/master/io/src/test/java/de.isas.lipidomics/io/MzTabValidatingWriterTest.java[MzTabValidatingWriterTest] - writing with structural and syntactic validation.
* https://github.com/lifs-tools/jmzTab-m/blob/master/io/src/test/java/de.isas.lipidomics/io/MzTabWriterTest.java[MzTabWriterTest] - plain writing of MzTab and roundtrip read/write/read testing.
* https://github.com/lifs-tools/jmzTab-m/blob/master/validation/src/test/java/de.isas.lipidomics/validation/ExampleFilesValidationTestIT.java[ExampleFilesValidationTestIT] - semantic validation using a mapping file and parameter validation rules.
* https://github.com/lifs-tools/jmzTab-m/blob/master/validation/src/test/java/de.isas.lipidomics/validation/JxPathTest.java[JxPathTest] - Object selection in MzTab models via the JxPath library.

== References

//This project is the reference implementation for the mzTab-M 2.0 standard:

//  * **https://pubs.acs.org/doi/10.1021/acs.analchem.8b04310[N. Hoffmann et al., Analytical Chemistry 2019; Jan;91(5):3302-3310.] https://pubs.acs.org/doi/pdf/10.1021/acs.analchem.8b04310[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/30688441[PubMed record].**

