//  Copyright 2019 nils.hoffmann.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
package de.isas.lipidomics.domain;

import de.isas.lipidomics.palinom.exceptions.ConstraintViolationException;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

/**
 * This class was generated by the LipidClassGenerator.
 *
 * Enumeration of lipid classes. The shorthand names / abbreviations are used to
 * look up the lipid class association of a lipid head group. We try to map each
 * abbreviation and synonyms thereof to LipidMAPS main class. However, not all
 * described head groups are categorized in LipidMAPS, or only occur in other
 * databases, so they do not have such an association at the moment.
 *
 * Example: Category=Glyerophospholipids -> Class=Glycerophosphoinositols (PI)
 *
 * @author nils.hoffmann
 */
public enum LipidClass {
    UNDEFINED(LipidCategory.UNDEFINED, "Undefined lipid class", "UNDEFINED"),
    FA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", "FA"),
    FA_10_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", "10-HDoHE"),
    FA_11_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", "11-HDoHE"),
    FA_11_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "11-HETE"),
    FA_11_12_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "11,12-DHET", "11,12-DiHETrE"),
    FA_11_12_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", "11(12)-EET", "11,12-EpETrE"),
    FA_12_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", "12-HEPE"),
    FA_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "12-HETE"),
    FA_12_HHTRE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatrienoic acids [FA0305]", "12-HHTrE"),
    FA_12_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", "12-OxoETE"),
    FA_12_13_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", "12(13)-EpOME"),
    FA_13_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", "13-HODE"),
    FA_13_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", "13-HOTrE"),
    FA_14_15_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "14,15-DHET", "14,15-DiHETrE"),
    FA_14_15_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", "14(15)-EET", "14,15-EpETrE"),
    FA_14_15_EPETE(LipidCategory.FA, "Other Eicosanoids [FA0300]", "14(15)-EpETE"),
    FA_15_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", "15-HEPE"),
    FA_15_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "15-HETE"),
    FA_15D_PGJ2(LipidCategory.FA, "Prostaglandins [FA0301]", "15d-PGJ2"),
    FA_16_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", "16-HDoHE"),
    FA_16_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "16-HETE"),
    FA_18_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", "18-HEPE"),
    FA_5_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", "5-HEPE"),
    FA_5_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "5-HETE"),
    FA_5_HPETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "5-HpETE"),
    FA_5_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", "5-OxoETE"),
    FA_5_12_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "5,12-DiHETE"),
    FA_5_6_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "5,6-DiHETE"),
    FA_5_6_15_LXA4(LipidCategory.FA, "Lipoxins [FA0304]", "5,6,15-LXA4"),
    FA_5_6_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", "5(6)-EET", "5,6-EpETrE"),
    FA_8_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", "8-HDoHE"),
    FA_8_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "8-HETE"),
    FA_8_9_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "8,9-DHET", "8,9-DiHETrE"),
    FA_8_9_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", "8(9)-EET", "8,9-EpETrE"),
    FA_9_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", "9-HEPE"),
    FA_9_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "9-HETE"),
    FA_9_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", "9-HODE"),
    FA_9_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", "9-HOTrE"),
    FA_9_10_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", "9(10)-EpOME"),
    AA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", "AA", "Arachidonic acid", "Arachidonic Acid"),
    ALPHA_LA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", "alpha-LA"),
    DHA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", "DHA", "Docosapentaenoic acid"),
    EPA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", "EPA", "Eicosapentaenoic acid"),
    GP_NAE(LipidCategory.FA, "X-ethanolamine", "GP-NAE"),
    LINOLEIC_ACID(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", "Linoleic acid"),
    LTB4(LipidCategory.FA, "Leukotrienes [FA0302]", "LTB4"),
    LTC4(LipidCategory.FA, "Leukotrienes [FA0302]", "LTC4"),
    LTD4(LipidCategory.FA, "Leukotrienes [FA0302]", "LTD4"),
    MARESIN_1(LipidCategory.FA, "Maresins [FA0405]", "Maresin 1"),
    NAE(LipidCategory.FA, "X-ethanolamine", "NAE"),
    PALMITIC_ACID(LipidCategory.FA, "Straight chain fatty acids [FA0101]", "Palmitic acid"),
    PGB2(LipidCategory.FA, "Prostaglandins [FA0301]", "PGB2"),
    PGD2(LipidCategory.FA, "Prostaglandins [FA0301]", "PGD2"),
    PGE2(LipidCategory.FA, "Prostaglandins [FA0301]", "PGE2"),
    PGF2ALPHA(LipidCategory.FA, "Prostaglandins [FA0301]", "PGF2alpha"),
    PGI2(LipidCategory.FA, "Prostaglandins [FA0301]", "PGI2"),
    RESOLVIN_D1(LipidCategory.FA, "Resolvin Ds [FA0403]", "Resolvin D1"),
    RESOLVIN_D2(LipidCategory.FA, "Resolvin Ds [FA0403]", "Resolvin D2"),
    RESOLVIN_D3(LipidCategory.FA, "Resolvin Ds [FA0403]", "Resolvin D3"),
    RESOLVIN_D5(LipidCategory.FA, "Resolvin Ds [FA0403]", "Resolvin D5"),
    TETRANOR_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", "tetranor-12-HETE"),
    TXB1(LipidCategory.FA, "Thromboxanes [FA0303]", "TXB1"),
    TXB2(LipidCategory.FA, "Thromboxanes [FA0303]", "TXB2"),
    TXB3(LipidCategory.FA, "Thromboxanes [FA0303]", "TXB3"),
    COA(LipidCategory.FA, "Fatty acyl CoAs [FA0705]", "CoA"),
    FAHFA(LipidCategory.FA, "Wax monoesters [FA0701]", "FAHFA"),
    DAG(LipidCategory.GL, "Diradylglycerols [GL02]", "DAG", "DG"),
    DGDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", "DGDG"),
    DHDG(LipidCategory.GL, "Dihexosyldiacylglycerol", "DHDG"),
    MAG(LipidCategory.GL, "Monoradylglycerols [GL01]", "MAG", "MG"),
    MGDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", "MGDG"),
    MHDG(LipidCategory.GL, "Monohexosyldiacylglycerol", "MHDG"),
    SQDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", "SQDG"),
    SQMG(LipidCategory.GL, "Glycosylmonoradylglycerols [GL04]", "SQMG"),
    TAG(LipidCategory.GL, "Triradylglycerols [GL03]", "TAG", "TG"),
    GP_6_AC_GLC_GP(LipidCategory.GP, "Glycosylglycerophospholipids [GP14]", "6-Ac-Glc-GP"),
    BMP(LipidCategory.GP, "Monoacylglycerophosphomonoradylglycerols [GP0410]", "BMP", "LBPA"),
    CDPDAG(LipidCategory.GP, "CDP-Glycerols [GP13]", "CDPDAG", "CDPDG", "CDP-DG", "CDP-DAG"),
    CL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", "CL"),
    CPA(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "CPA"),
    DLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", "DLCL"),
    DMPE(LipidCategory.GP, "Dimethylphosphatidylethanolamine", "DMPE"),
    GLC_DG(LipidCategory.GP, "Glycosyldiradylglycerols [GL05]", "Glc-DG"),
    GLC_GP(LipidCategory.GP, "Glycosylglycerophospholipids [GP14]", "Glc-GP"),
    LCDPDAG(LipidCategory.GP, "Lyso-CDP-diacylglycerol", "LCDPDAG"),
    LDMPE(LipidCategory.GP, "Lysodimethylphosphatidylethanolamine", "LDMPE"),
    LMMPE(LipidCategory.GP, "Lysomonomethylphosphatidylethanolamine", "LMMPE"),
    LPA(LipidCategory.GP, "Glycerophosphates [GP10]", "LPA"),
    LPC(LipidCategory.GP, "Glycerophosphocholines [GP01]", "LPC", "LysoPC"),
    LPE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "LPE", "LysoPE"),
    LPG(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", "LPG"),
    LPI(LipidCategory.GP, "Glycerophosphoinositols [GP06]", "LPI"),
    LPIM1(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM1"),
    LPIM2(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM2"),
    LPIM3(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM3"),
    LPIM4(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM4"),
    LPIM5(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM5"),
    LPIM6(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "LPIM6"),
    LPIMIP(LipidCategory.GP, "Lysophosphatidylinositol- mannosideinositolphosphate", "LPIMIP"),
    LPIN(LipidCategory.GP, "Lysophosphatidylinositol-glucosamine", "LPIN"),
    LPS(LipidCategory.GP, "Glycerophosphoserines [GP03]", "LPS"),
    MLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", "MLCL"),
    NAPE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "NAPE"),
    PA(LipidCategory.GP, "Glycerophosphates [GP10]", "PA"),
    PC(LipidCategory.GP, "Glycerophosphocholines [GP01]", "PC"),
    PE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "PE"),
    PE_NME(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "PE-NMe"),
    PE_NME2(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "PE-NMe2"),
    PET(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", "PEt"),
    PG(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", "PG"),
    PGP(LipidCategory.GP, "Glycerophosphoglycerophosphates [GP05]", "PGP"),
    PI(LipidCategory.GP, "Glycerophosphoinositols [GP06]", "PI"),
    PIM1(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM1"),
    PIM2(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM2"),
    PIM3(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM3"),
    PIM4(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM4"),
    PIM5(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM5"),
    PIM6(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PIM6"),
    PIMIP(LipidCategory.GP, "Phosphatidylinositol mannoside inositol phosphate", "PIMIP"),
    PIP(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", "PIP"),
    PIP_3P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", "PIP[3']", "PIP[3]"),
    PIP_4P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", "PIP[4']", "PIP[4]"),
    PIP_5P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", "PIP[5']", "PIP[5]"),
    PIP2(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", "PIP2"),
    PIP2_3P_4P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", "PIP2[3',4']", "PIP2[3,4]"),
    PIP2_3P_5P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", "PIP2[3',5']", "PIP2[3,5]"),
    PIP2_4P_5P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", "PIP2[4',5']", "PIP2[4,5]"),
    PIP3(LipidCategory.GP, "Glycerophosphoinositol trisphosphates [GP09]", "PIP3"),
    PIP3_3P_4P_5P_(LipidCategory.GP, "Glycerophosphoinositol trisphosphates [GP09]", "PIP3[3',4',5']", "PIP3[3,4,5]"),
    PNC(LipidCategory.GP, "Glycerophosphonocholines [GP16]", "PnC"),
    PNE(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PnE"),
    PPA(LipidCategory.GP, "Glyceropyrophosphates [GP11]", "PPA"),
    PS(LipidCategory.GP, "Glycerophosphoserines [GP03]", "PS"),
    PT(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", "PT"),
    SLBPA(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", "SLBPA"),
    AC2SGL(LipidCategory.SL, "Acyltrehaloses [SL03]", "AC2SGL"),
    DAT(LipidCategory.SL, "Acyltrehaloses [SL03]", "DAT"),
    PAT16(LipidCategory.SL, "Acyltrehaloses [SL03]", "PAT16"),
    PAT18(LipidCategory.SL, "Acyltrehaloses [SL03]", "PAT18"),
    SP_3P_SULFO_LACCER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "(3'-sulfo)LacCer"),
    SP_FUC_IGB3CER(LipidCategory.SP, "Globoside", "(Fuc)iGb3Cer"),
    AC_O_9_GD1A(LipidCategory.SP, "Globoside", "Ac-O-9-GD1a"),
    AC_O_9_GT1B(LipidCategory.SP, "Globoside", "Ac-O-9-GT1b"),
    AC_O_9_GT3(LipidCategory.SP, "Globoside", "Ac-O-9-GT3"),
    BRANCHED_FORSSMAN(LipidCategory.SP, "Globoside", "Branched-Forssman"),
    C1P(LipidCategory.SP, "Ceramide-1-phosphates [SP0205]", "C1P"),
    CER(LipidCategory.SP, "Ceramides [SP02]", "Cer"),
    CERP(LipidCategory.SP, "Ceramides [SP02]", "CerP"),
    DSGG(LipidCategory.SP, "Globoside", "DSGG"),
    EPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", "EPC", "PE-Cer"),
    FMC_5(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "FMC-5"),
    FMC_6(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "FMC-6"),
    FORSSMAN(LipidCategory.SP, "Globoside", "Forssman"),
    FUC_BRANCHED_FORSSMAN(LipidCategory.SP, "Globoside", "Fuc-Branched-Forssman"),
    FUC_GA1(LipidCategory.SP, "Globoside", "Fuc-GA1"),
    FUC_GD1B(LipidCategory.SP, "Globoside", "Fuc-GD1b"),
    FUC_GM1(LipidCategory.SP, "Globoside", "Fuc-GM1"),
    FUC_GM1_NEUGC_(LipidCategory.SP, "Globoside", "Fuc-GM1(NeuGc)"),
    FUC_IGB3CER(LipidCategory.SP, "Globoside", "Fuc-iGb3Cer"),
    FUC_GAL_GM1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "Fuc(Gal)-GM1"),
    FUC_GAL_GAL_IGB4CER(LipidCategory.SP, "Globoside", "Fuc(Gal)Gal-iGb4Cer"),
    FUCGALGB3CER(LipidCategory.SP, "Globoside", "FucGalGb3Cer"),
    GA1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GA1"),
    GA2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GA2"),
    GAL_GD1B(LipidCategory.SP, "Globoside", "Gal-GD1b"),
    GAL_IGB4CER(LipidCategory.SP, "Globoside", "Gal-iGb4Cer"),
    GAL_FUC_GA1(LipidCategory.SP, "Globoside", "Gal(Fuc)-GA1"),
    GAL_FUC_GD1B(LipidCategory.SP, "Globoside", "Gal(Fuc)-GD1b"),
    GALGAL_GD1B(LipidCategory.SP, "Globoside", "GalGal-GD1b"),
    GALGALGALGB3CER(LipidCategory.SP, "Globoside", "GalGalGalGb3Cer"),
    GALGALGB3CER(LipidCategory.SP, "Globoside", "GalGalGb3Cer"),
    GALGALNAC_GM1B_NEUGC_(LipidCategory.SP, "Globoside", "GalGalNAc-GM1b(NeuGc)"),
    GALGB3CER(LipidCategory.SP, "Globoside", "GalGb3Cer"),
    GALGB4CER(LipidCategory.SP, "Globoside", "GalGb4Cer"),
    GALGLCNAC_GALGB4CER(LipidCategory.SP, "Globoside", "GalGlcNAc-GalGb4Cer"),
    GALNAC_GD1A(LipidCategory.SP, "Globoside", "GalNAc-GD1a"),
    GALNAC_GD1A_NEUGC_NEUAC_(LipidCategory.SP, "Globoside", "GalNAc-GD1a(NeuGc/NeuAc)"),
    GALNAC_GM1(LipidCategory.SP, "Globoside", "GalNAc-GM1"),
    GALNAC_GM1B(LipidCategory.SP, "Globoside", "GalNAc-GM1b"),
    GALNAC_GM1B_NEUGC_(LipidCategory.SP, "Globoside", "GalNAc-GM1b(NeuGc)"),
    GALNACGAL_FUC_GA1(LipidCategory.SP, "Globoside", "GalNAcGal(Fuc)-GA1"),
    GALNACGALGB3CER(LipidCategory.SP, "Globoside", "GalNAcGalGb3Cer"),
    GB3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "Gb3"),
    GB3CER(LipidCategory.SP, "Globoside", "Gb3Cer"),
    GB4(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "GB4"),
    GB4CER(LipidCategory.SP, "Globoside", "Gb4Cer"),
    GD1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD1"),
    GD1A(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD1a"),
    GD1A_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids", "GD1a alpha"),
    GD1A_NEUAC_NEUGC_(LipidCategory.SP, "Globoside", "GD1a(NeuAc/NeuGc)"),
    GD1A_NEUGC_NEUAC_(LipidCategory.SP, "Globoside", "GD1a(NeuGc/NeuAc)"),
    GD1A_NEUGC_NEUGC_(LipidCategory.SP, "Globoside", "GD1a(NeuGc/NeuGc)"),
    GD1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD1b"),
    GD1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD1c"),
    GD1C_NEUGC_NEUGC_(LipidCategory.SP, "Globoside", "GD1c(NeuGc/NeuGc)"),
    GD2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD2"),
    GD3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GD3"),
    GLCNAC_GALGB4CER(LipidCategory.SP, "Globoside", "GlcNAc-GalGb4Cer"),
    GLCNACGB3CER(LipidCategory.SP, "Globoside", "GlcNAcGb3Cer"),
    GLOBO_A(LipidCategory.SP, "Globoside", "Globo-A"),
    GLOBO_B(LipidCategory.SP, "Globoside", "Globo-B"),
    GLOBO_H(LipidCategory.SP, "Globoside", "Globo-H"),
    GLOBO_LEX_9(LipidCategory.SP, "Globoside", "Globo-Lex-9"),
    GM1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GM1"),
    GM1_ALPHA(LipidCategory.SP, "Globoside", "GM1 alpha"),
    GM1_NEUGC_(LipidCategory.SP, "Globoside", "GM1(NeuGc)"),
    GM1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GM1b"),
    GM1B_NEUGC_(LipidCategory.SP, "Globoside", "GM1b(NeuGc)"),
    GM2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GM2"),
    GM2_NEUGC_(LipidCategory.SP, "Globoside", "GM2(NeuGc)"),
    GM3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GM3"),
    GM4(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GM4"),
    GP1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GP1"),
    GP1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GP1c"),
    GP1C_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GP1c alpha"),
    GQ1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GQ1"),
    GQ1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GQ1b"),
    GQ1B_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GQ1b alpha"),
    GQ1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GQ1c"),
    GT1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT1"),
    GT1A(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT1a"),
    GT1A_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT1a alpha"),
    GT1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT1b"),
    GT1B_ALPHA(LipidCategory.SP, "Globoside", "GT1b alpha"),
    GT1B_ALPHA_NEUGC_(LipidCategory.SP, "Globoside", "GT1b alpha(NeuGc)"),
    GT1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT1c"),
    GT2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT2"),
    GT3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "GT3"),
    HEX2CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "Hex2Cer", "LacCer"),
    HEX3CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "Hex3Cer", "GB3"),
    HEXCER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", "HexCer", "GalCer", "GlcCer", "(3'-sulfo)GalCer"),
    I_FORSSMAN(LipidCategory.SP, "Globoside", "i-Forssman"),
    IGB3CER(LipidCategory.SP, "Globoside", "iGb3Cer"),
    IGB4CER(LipidCategory.SP, "Globoside", "iGb4Cer"),
    IPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", "IPC", "PI-Cer"),
    LCB(LipidCategory.SP, "Sphingoid bases [SP01]", "LCB", "Sphingosine", "So", "Sphingosine-1-phosphate", "SPH"),
    LCBP(LipidCategory.SP, "Sphingoid bases [SP01]", "LCBP", "Sphinganine", "Sa", "Sphingosine-1-phosphate", "S1P", "SPH-P"),
    LEX_GM1(LipidCategory.SP, "Globoside", "Lex-GM1"),
    LHEXCER(LipidCategory.SP, "Hexosylsphingosine", "LHexCer", "HexSph"),
    LSM(LipidCategory.SP, "Ceramides [SP02]", "LSM", "SPC"),
    M_IP_2C(LipidCategory.SP, "Phosphosphingolipids [SP03]", "M(IP)2C"),
    MIPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", "MIPC"),
    MSGG(LipidCategory.SP, "Globoside", "MSGG"),
    NEUAC_ALPHA2_6_MSGG(LipidCategory.SP, "Globoside", "NeuAc(alpha2-6)-MSGG"),
    NEUAC_ALPHA2_8_MSGG(LipidCategory.SP, "Globoside", "NeuAc(alpha2-8)-MSGG"),
    NEUACGAL_IGB4CER(LipidCategory.SP, "Globoside", "NeuAcGal-iGb4Cer"),
    NEUGC_GALGB4CER(LipidCategory.SP, "Globoside", "NeuGc-GalGb4Cer"),
    NEUGC_LACNAC_GM1_NEUGC_(LipidCategory.SP, "Globoside", "NeuGc-LacNAc-GM1(NeuGc)"),
    NEUGCNEUGC_GALGB4CER(LipidCategory.SP, "Globoside", "NeuGcNeuGc-GalGb4Cer"),
    NOR1(LipidCategory.SP, "Globoside", "NOR1"),
    NOR2(LipidCategory.SP, "Globoside", "NOR2"),
    NORINT(LipidCategory.SP, "Globoside", "NORint"),
    PARA_FORSSMAN(LipidCategory.SP, "Globoside", "Para-Forssman"),
    SB1A(LipidCategory.SP, "Globoside", "SB1a"),
    SHEX2CER(LipidCategory.SP, "Sulfodihexosyl ceramide", "SHex2Cer", "SulfoHex2Cer"),
    SHEXCER(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "SHexCer", "SulfoHexCer", "(3'-sulfo)Galbeta-Cer"),
    SM(LipidCategory.SP, "Phosphosphingolipids [SP03]", "SM"),
    SM1A(LipidCategory.SP, "Globoside", "SM1a"),
    SM1B(LipidCategory.SP, "Globoside", "SM1b"),
    SO3_GAL_IGB4CER(LipidCategory.SP, "Globoside", "SO3-Gal-iGb4Cer"),
    SO3_GALGB4CER(LipidCategory.SP, "Globoside", "SO3-GalGb4Cer"),
    SO3_GB4CER(LipidCategory.SP, "Globoside", "SO3-Gb4Cer"),
    SO3_GM1_NEUGC_(LipidCategory.SP, "Globoside", "SO3-GM1(NeuGc)"),
    SO3_IGB4CER(LipidCategory.SP, "Globoside", "SO3-iGb4Cer"),
    SULFOGALCER(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", "SulfoGalCer"),
    CH(LipidCategory.ST, "Cholesterol [LMST01010001]", "CH", "FC", "Cholesterol"),
    CHE(LipidCategory.ST, "Cholesteryl esters [ST0102]", "ChE", "CE", "Cholesteryl ester", "Cholesterol ester"),
    SE(LipidCategory.ST, "Steryl esters [ST0102]", "SE"),
    ST(LipidCategory.ST, "Sterols [ST01]", "ST"),
    WE(LipidCategory.FA, "Fatty esters [FA07]", "WE");

    private final LipidCategory category;

    private final String lipidMapsClassName;

    private final List<String> synonyms;

    private LipidClass(LipidCategory category, String lipidMapsClassName, String... synonyms) {
        this.category = category;
        this.lipidMapsClassName = lipidMapsClassName;
        if (synonyms.length == 0) {
            throw new IllegalArgumentException("Must supply at least one synonym!");
        };
        this.synonyms = Arrays.asList(synonyms);
    }

    public LipidCategory getCategory() {
        return this.category;
    }

    public String getAbbreviation() {
        return this.synonyms.get(0);
    }

    public String getLipidMapsClassName() {
        return this.lipidMapsClassName;
    }

    public List<String> getSynonyms() {
        return this.synonyms;
    }

    public boolean matchesAbbreviation(String headGroup) {
        return this.synonyms.stream().anyMatch((synonym) -> {
            return synonym.equals(headGroup);
        });
    }

    public String getLysoAbbreviation(LipidClass lipidClass) {
        if (lipidClass.getCategory() == LipidCategory.GP) {
            return "L" + lipidClass.getAbbreviation();
        }
        throw new ConstraintViolationException("Lipid category must be " + LipidCategory.GP + " for lyso-classes!");
    }

    public static Optional<LipidClass> forHeadGroup(String headGroup) {
        return Arrays.asList(values()).stream().filter((lipidClass) -> {
            return lipidClass.matchesAbbreviation(headGroup.trim());
        }).findFirst();
    }
}
