//  Copyright 2019 nils.hoffmann.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
package de.isas.lipidomics.domain;

import de.isas.lipidomics.palinom.exceptions.ConstraintViolationException;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

/**
 * This class was generated by the LipidClassGenerator.
 *
 * Enumeration of lipid classes. The shorthand names / abbreviations are used to
 * look up the lipid class association of a lipid head group. We try to map each
 * abbreviation and synonyms thereof to LipidMAPS main class. However, not all
 * described head groups are categorized in LipidMAPS, or only occur in other
 * databases, so they do not have such an association at the moment.
 *
 * Example: Category=Glyerophospholipids maps to Class=Glycerophosphoinositols
 * (PI)
 *
 * @author nils.hoffmann
 */
public enum LipidClass {
    SP_3P_SULFO_LACCER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C12H20O13S", java.util.Arrays.asList("(3'-sulfo)LacCer")),
    SP_FUC_IGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C24H41O19", java.util.Arrays.asList("(Fuc)iGb3Cer")),
    SP_1_O_BEHENOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C22H43O", java.util.Arrays.asList("1-O-behenoyl-Cer")),
    SP_1_O_CARBOCEROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C28H55O", java.util.Arrays.asList("1-O-carboceroyl-Cer")),
    SP_1_O_CEROTOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C26H51O", java.util.Arrays.asList("1-O-cerotoyl-Cer")),
    SP_1_O_EICOSANOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C20H39O", java.util.Arrays.asList("1-O-eicosanoyl-Cer")),
    SP_1_O_LIGNOCEROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C24H47O", java.util.Arrays.asList("1-O-lignoceroyl-Cer")),
    SP_1_O_MYRISTOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C14H27O", java.util.Arrays.asList("1-O-myristoyl-Cer")),
    SP_1_O_PALMITOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C16H31O", java.util.Arrays.asList("1-O-palmitoyl-Cer")),
    SP_1_O_STEAROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C18H35O", java.util.Arrays.asList("1-O-stearoyl-Cer")),
    SP_1_O_TRICOSANOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "C70H59O", java.util.Arrays.asList("1-O-tricosanoyl-Cer")),
    FA_10_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "C22H32O3", java.util.Arrays.asList("10-HDoHE")),
    FA_11_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "C22H32O3", java.util.Arrays.asList("11-HDoHE")),
    FA_11_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("11-HETE")),
    FA_11_12_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H34O4", java.util.Arrays.asList("11,12-DHET", "11,12-DiHETrE")),
    FA_11_12_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "C20H32O3", java.util.Arrays.asList("11(12)-EET", "11,12-EpETrE")),
    FA_12_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "C20H30O3", java.util.Arrays.asList("12-HEPE")),
    FA_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("12-HETE")),
    FA_12_HHTRE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatrienoic acids [FA0305]", 0, "0", "C17H28O3", java.util.Arrays.asList("12-HHTrE")),
    FA_12_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "C20H30O3", java.util.Arrays.asList("12-OxoETE")),
    FA_12_13_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H32O3", java.util.Arrays.asList("12(13)-EpOME")),
    FA_13_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H32O3", java.util.Arrays.asList("13-HODE")),
    FA_13_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H30O3", java.util.Arrays.asList("13-HOTrE")),
    FA_14_15_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H34O4", java.util.Arrays.asList("14,15-DHET", "14,15-DiHETrE")),
    FA_14_15_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "C20H32O3", java.util.Arrays.asList("14(15)-EET", "14,15-EpETrE")),
    FA_14_15_EPETE(LipidCategory.FA, "Other Eicosanoids [FA0300]", 0, "0", "C20H30O3", java.util.Arrays.asList("14(15)-EpETE")),
    FA_15_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "C20H30O3", java.util.Arrays.asList("15-HEPE")),
    FA_15_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("15-HETE")),
    FA_15D_PGJ2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H28O3", java.util.Arrays.asList("15d-PGJ2")),
    FA_16_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "C22H32O3", java.util.Arrays.asList("16-HDoHE")),
    FA_16_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("16-HETE")),
    FA_18_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "C20H30O3", java.util.Arrays.asList("18-HEPE")),
    FA_5_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "C20H30O3", java.util.Arrays.asList("5-HEPE")),
    FA_5_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("5-HETE")),
    FA_5_HPETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O4", java.util.Arrays.asList("5-HpETE")),
    FA_5_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "C20H30O3", java.util.Arrays.asList("5-OxoETE")),
    FA_5_12_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O4", java.util.Arrays.asList("5,12-DiHETE")),
    FA_5_6_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O4", java.util.Arrays.asList("5,6-DiHETE")),
    FA_5_6_15_LXA4(LipidCategory.FA, "Lipoxins [FA0304]", 0, "0", "C20H32O5", java.util.Arrays.asList("5,6,15-LXA4")),
    FA_5_6_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "C20H32O3", java.util.Arrays.asList("5(6)-EET", "5,6-EpETrE")),
    GP_6_AC_GLC_GP(LipidCategory.GP, "Glycosylglycerophospholipids [GP14]", 2, "2", "C11H19O12P", java.util.Arrays.asList("6-Ac-Glc-GP")),
    FA_8_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "C22H32O3", java.util.Arrays.asList("8-HDoHE")),
    FA_8_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("8-HETE")),
    FA_8_9_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H34O4", java.util.Arrays.asList("8,9-DHET", "8,9-DiHETrE")),
    FA_8_9_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "C20H32O3", java.util.Arrays.asList("8(9)-EET", "8,9-EpETrE")),
    FA_9_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "C20H30O3", java.util.Arrays.asList("9-HEPE")),
    FA_9_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C20H32O3", java.util.Arrays.asList("9-HETE")),
    FA_9_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H32O3", java.util.Arrays.asList("9-HODE")),
    FA_9_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H30O3", java.util.Arrays.asList("9-HOTrE")),
    FA_9_10_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "C18H32O3", java.util.Arrays.asList("9(10)-EpOME")),
    AA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "C20H32O2", java.util.Arrays.asList("AA", "Arachidonic acid", "Arachidonic Acid")),
    AC_O_9_GD1A(LipidCategory.SP, "Globoside", 2, "2", "C50H78N3O37", java.util.Arrays.asList("Ac-O-9-GD1a")),
    AC_O_9_GT1B(LipidCategory.SP, "Globoside", 2, "2", "C61H94N4O45", java.util.Arrays.asList("Ac-O-9-GT1b")),
    AC_O_9_GT3(LipidCategory.SP, "Globoside", 2, "2", "C47H71N3O35", java.util.Arrays.asList("Ac-O-9-GT3")),
    AC2SGL(LipidCategory.SL, "Acyltrehaloses [SL03]", 2, "2", "C20H36O14S", java.util.Arrays.asList("AC2SGL")),
    ALPHA_LA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "", java.util.Arrays.asList("alpha-LA", "ALA")),
    ANACARD(LipidCategory.PK, "Anacardic acids and derivatives [PK1504]", 2, "2", "", java.util.Arrays.asList("ANACARD")),
    BMP(LipidCategory.GP, "Monoacylglycerophosphomonoradylglycerols [GP0410]", 4, "4", "C6H11O8P", java.util.Arrays.asList("BMP")),
    BRANCHED_FORSSMAN(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C48H80N3O35", java.util.Arrays.asList("Branched-Forssman")),
    CAR(LipidCategory.FA, "Fatty acyl carnitines [FA0707]", 2, "2", "", java.util.Arrays.asList("CAR")),
    CATECHOL(LipidCategory.PK, "Alkyl catechols and derivatives [PK1502]", 2, "2", "", java.util.Arrays.asList("CATECHOL")),
    CDPDAG(LipidCategory.GP, "CDP-diacylglycerols [GP1301]", 2, "2", "C12H19N3O13P2", java.util.Arrays.asList("CDPDAG", "CDPDG", "CDP-DG", "CDP-DAG")),
    CER(LipidCategory.SP, "Ceramides [SP02]", 2, "2", "H", java.util.Arrays.asList("Cer", "Ceramide")),
    CERP(LipidCategory.SP, "Ceramide 1-phosphates [SP0205]", 2, "2", "H2O3P", java.util.Arrays.asList("CerP", "C1P")),
    CL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "4", "C9H18O13P2", java.util.Arrays.asList("CL")),
    COA(LipidCategory.FA, "Fatty acyl CoAs [FA0705]", 1, "1", "C21H35N7O16P3S", java.util.Arrays.asList("CoA")),
    CPA(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 1, "1", "C3H6O5P", java.util.Arrays.asList("CPA")),
    DAG(LipidCategory.GL, "Diacylglycerols [GL0201]", 3, "2", "C3H5O3", java.util.Arrays.asList("DAG", "DG")),
    DAT(LipidCategory.SL, "Acyltrehaloses [SL03]", 2, "2", "C15H26O11", java.util.Arrays.asList("DAT")),
    DGCC(LipidCategory.GL, "Other Glycerolipids [GL00]", 2, "2", "C10H19NO6", java.util.Arrays.asList("DGCC")),
    DGDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "C15H26O13", java.util.Arrays.asList("DGDG")),
    DHA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "C22H32O2", java.util.Arrays.asList("DHA", "Docosapentaenoic acid")),
    DHDG(LipidCategory.GL, "Dihexosyldiacylglycerol", 2, "2", "C15H26O13", java.util.Arrays.asList("DHDG")),
    DLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "2", "C9H16O13P2", java.util.Arrays.asList("DLCL")),
    DMPE(LipidCategory.GP, "Dimethylphosphatidylethanolamine", 2, "2", "C7H16NO6P", java.util.Arrays.asList("DMPE")),
    DSGG(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C54H86N3O41", java.util.Arrays.asList("DSGG")),
    EPA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "C20H30O2", java.util.Arrays.asList("EPA", "Eicosapentaenoic acid")),
    EPC(LipidCategory.SP, "Ceramide phosphoethanolamines [SP0302]", 2, "2", "C2H7NO3P", java.util.Arrays.asList("EPC", "PE-Cer")),
    FA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 1, "1", "HO", java.util.Arrays.asList("FA")),
    FAHFA(LipidCategory.FA, "Wax monoesters [FA0701]", 0, "0", "", java.util.Arrays.asList("FAHFA")),
    FMC_5(LipidCategory.SP, "Simple Glc series [SP0501]", 2, "2", "C16H21O10", java.util.Arrays.asList("FMC-5")),
    FMC_6(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C9H18O11P", java.util.Arrays.asList("FMC-6")),
    FORSSMAN(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C34H57N2O25", java.util.Arrays.asList("Forssman")),
    FUC_BRANCHED_FORSSMAN(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C54H90N3O39", java.util.Arrays.asList("Fuc-Branched-Forssman")),
    FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "C32H54NO24", java.util.Arrays.asList("Fuc-GA1")),
    FUC_GD1B(LipidCategory.SP, "Globoside", 2, "2", "C54H86N3O40", java.util.Arrays.asList("Fuc-GD1b")),
    FUC_GM1(LipidCategory.SP, "Globoside", 2, "2", "C43H70N2O32", java.util.Arrays.asList("Fuc-GM1")),
    FUC_GM1_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C43H70N2O33", java.util.Arrays.asList("Fuc-GM1(NeuGc)")),
    FUC_IGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C24H41O19", java.util.Arrays.asList("Fuc-iGb3Cer")),
    FUC_GAL_GM1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "C49H80N2O37", java.util.Arrays.asList("Fuc(Gal)-GM1")),
    FUC_GAL_GAL_IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C44H74NO34", java.util.Arrays.asList("Fuc(Gal)Gal-iGb4Cer")),
    FUCGALGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C30H51O24", java.util.Arrays.asList("FucGalGb3Cer")),
    GA1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H44NO20", java.util.Arrays.asList("GA1")),
    GA2(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C20H34NO15", java.util.Arrays.asList("GA2")),
    GAL_GD1B(LipidCategory.SP, "Globoside", 2, "2", "C54H86N3O41", java.util.Arrays.asList("Gal-GD1b")),
    GAL_IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C32H54NO25", java.util.Arrays.asList("Gal-iGb4Cer")),
    GAL_FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "C38H64NO29", java.util.Arrays.asList("Gal(Fuc)-GA1")),
    GAL_FUC_GD1B(LipidCategory.SP, "Globoside", 2, "2", "C60H96N3O45", java.util.Arrays.asList("Gal(Fuc)-GD1b")),
    GALGAL_GD1B(LipidCategory.SP, "Globoside", 2, "2", "C60H96N3O46", java.util.Arrays.asList("GalGal-GD1b")),
    GALGALGALGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C36H61O30", java.util.Arrays.asList("GalGalGalGb3Cer")),
    GALGALGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C30H51O25", java.util.Arrays.asList("GalGalGb3Cer")),
    GALGALNAC_GM1B_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C51H83N3O39", java.util.Arrays.asList("GalGalNAc-GM1b(NeuGc)")),
    GALGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C24H41O20", java.util.Arrays.asList("GalGb3Cer")),
    GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C32H54NO25", java.util.Arrays.asList("GalGb4Cer")),
    GALGLCNAC_GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C46H77N2O35", java.util.Arrays.asList("GalGlcNAc-GalGb4Cer")),
    GALNAC_GD1A(LipidCategory.SP, "Globoside", 2, "2", "C56H89N4O41", java.util.Arrays.asList("GalNAc-GD1a")),
    GALNAC_GD1A_NEUAC_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C56H89N4O42", java.util.Arrays.asList("GalNAc-GD1a(NeuAc/NeuGc)")),
    GALNAC_GD1A_NEUGC_NEUAC(LipidCategory.SP, "Globoside", 2, "2", "C56H89N4O42", java.util.Arrays.asList("GalNAc-GD1a(NeuGc/NeuAc)")),
    GALNAC_GM1(LipidCategory.SP, "Globoside", 2, "2", "C45H73N3O33", java.util.Arrays.asList("GalNAc-GM1")),
    GALNAC_GM1B(LipidCategory.SP, "Globoside", 2, "2", "C45H73N3O33", java.util.Arrays.asList("GalNAc-GM1b")),
    GALNAC_GM1B_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C45H73N3O34", java.util.Arrays.asList("GalNAc-GM1b(NeuGc)")),
    GALNACGAL_FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "C46H77N2O34", java.util.Arrays.asList("GalNAcGal(Fuc)-GA1")),
    GALNACGALGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C32H54NO25", java.util.Arrays.asList("GalNAcGalGb3Cer")),
    GB3(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C18H31O15", java.util.Arrays.asList("GB3", "Gb3")),
    GB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C18H31O15", java.util.Arrays.asList("GB3Cer", "Gb3Cer")),
    GB4(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C26H44NO20", java.util.Arrays.asList("GB4", "Gb4")),
    GB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H44NO20", java.util.Arrays.asList("GB4Cer", "Tetrahexosylceramide", "Gb4Cer")),
    GD1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1")),
    GD1A(LipidCategory.SP, "Ganglioside GD1a(d18:1(4E))", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1a")),
    GD1A_ALPHA(LipidCategory.SP, "Ganglioside GD1a alpha(d18:1(4E))", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1a alpha")),
    GD1A_NEUAC_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1a(NeuAc/NeuGc)")),
    GD1A_NEUGC_NEUAC(LipidCategory.SP, "Globoside", 2, "2", "C48H76N3O37", java.util.Arrays.asList("GD1a(NeuGc/NeuAc)")),
    GD1A_NEUGC_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C48H76N3O38", java.util.Arrays.asList("GD1a(NeuGc/NeuGc)")),
    GD1B(LipidCategory.SP, "Ganglioside GD1b(d18:1(4E))", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1b")),
    GD1C(LipidCategory.SP, "Ganglioside GD1c(d18:1(4E))", 2, "2", "C48H76N3O36", java.util.Arrays.asList("GD1c")),
    GD1C_NEUGC_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C48H76N3O38", java.util.Arrays.asList("GD1c(NeuGc/NeuGc)")),
    GD2(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C42H66N3O31", java.util.Arrays.asList("GD2")),
    GD3(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C34H55N2O26", java.util.Arrays.asList("GD3")),
    GLC_DG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "", java.util.Arrays.asList("Glc-DG")),
    GLC_GP(LipidCategory.GP, "Diacylglycosylglycerophospholipids [GP1401]", 2, "2", "C9H17O11P", java.util.Arrays.asList("Glc-GP")),
    GLCNAC_GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C40H67N2O30", java.util.Arrays.asList("GlcNAc-GalGb4Cer")),
    GLCNACGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H44NO20", java.util.Arrays.asList("GlcNAcGb3Cer")),
    GLOBO_A(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C46H77N2O34", java.util.Arrays.asList("Globo-A")),
    GLOBO_B(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C44H74NO34", java.util.Arrays.asList("Globo-B")),
    GLOBO_H(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C38H64NO29", java.util.Arrays.asList("Globo-H")),
    GLOBO_LEX_9(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C52H87N2O39", java.util.Arrays.asList("Globo-Lex-9")),
    GM1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C37H60N2O28", java.util.Arrays.asList("GM1")),
    GM1_ALPHA(LipidCategory.SP, "Globoside", 2, "2", "C37H60N2O28", java.util.Arrays.asList("GM1 alpha")),
    GM1_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C37H60N2O28", java.util.Arrays.asList("GM1(NeuGc)")),
    GM1B(LipidCategory.SP, "Ganglioside GM1b(d18:1(4E))", 2, "2", "C37H60N2O28", java.util.Arrays.asList("GM1b")),
    GM1B_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C37H60N2O29", java.util.Arrays.asList("GM1b(NeuGc)")),
    GM2(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C31H50N2O23", java.util.Arrays.asList("GM2")),
    GM2_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C31H50N2O24", java.util.Arrays.asList("GM2(NeuGc)")),
    GM3(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C23H38NO18", java.util.Arrays.asList("GM3")),
    GM4(LipidCategory.SP, "Gangliosides [SP0601]", 2, "2", "C17H28NO13", java.util.Arrays.asList("GM4")),
    GP_NAE(LipidCategory.FA, "Glycerophosphoethanolamine", 0, "0", "C5H12NO6P", java.util.Arrays.asList("GP-NAE")),
    GP1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C81H124N6O60", java.util.Arrays.asList("GP1")),
    GP1C(LipidCategory.SP, "Ganglioside GP1c(d18:1(4E))", 2, "2", "C81H124N6O60", java.util.Arrays.asList("GP1c")),
    GP1C_ALPHA(LipidCategory.SP, "Ganglioside GP1c alpha(d18:1(4E))", 2, "2", "C81H124N6O60", java.util.Arrays.asList("GP1c alpha")),
    GQ1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C70H108N5O52", java.util.Arrays.asList("GQ1")),
    GQ1B(LipidCategory.SP, "Ganglioside GQ1b(d18:1(4E))", 2, "2", "C70H108N5O52", java.util.Arrays.asList("GQ1b")),
    GQ1B_ALPHA(LipidCategory.SP, "Ganglioside GQ1b alpha(d18:1(4E))", 2, "2", "C70H108N5O52", java.util.Arrays.asList("GQ1b alpha")),
    GQ1C(LipidCategory.SP, "Ganglioside GQ1c(d18:1(4E))", 2, "2", "C70H108N5O52", java.util.Arrays.asList("GQ1c")),
    GT1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1")),
    GT1A(LipidCategory.SP, "Ganglioside GT1a(d18:1(4E))", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1a")),
    GT1A_ALPHA(LipidCategory.SP, "Ganglioside GT1a alpha(d18:1(4E))", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1a alpha")),
    GT1B(LipidCategory.SP, "Ganglioside GT1b(d18:1(4E))", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1b")),
    GT1B_ALPHA(LipidCategory.SP, "Globoside", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1b alpha")),
    GT1B_ALPHA_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C59H92N4O45", java.util.Arrays.asList("GT1b alpha(NeuGc)")),
    GT1C(LipidCategory.SP, "Ganglioside GT1c(d18:1(4E))", 2, "2", "C59H92N4O44", java.util.Arrays.asList("GT1c")),
    GT2(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C53H82N4O39", java.util.Arrays.asList("GT2")),
    GT3(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C45H69N3O34", java.util.Arrays.asList("GT3")),
    HEX2CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C12H21O10", java.util.Arrays.asList("Hex2Cer", "LacCer")),
    HEX3CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C18H31O15", java.util.Arrays.asList("Hex3Cer", "GB3")),
    HEXCER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "C6H11O5", java.util.Arrays.asList("HexCer", "GalCer", "GlcCer", "Glucosylceramide")),
    I_FORSSMAN(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C34H57N2O25", java.util.Arrays.asList("i-Forssman")),
    IGB3CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C18H31O15", java.util.Arrays.asList("iGb3Cer")),
    IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H44NO20", java.util.Arrays.asList("iGb4Cer")),
    IPC(LipidCategory.SP, "Ceramide phosphoinositols [SP0303]", 2, "2", "C6H12O8P", java.util.Arrays.asList("IPC", "PI-Cer")),
    LBPA(LipidCategory.GP, "Monoacylglycerophosphomonoradylglycerols [GP0410]", 4, "2", "C6H11O8P", java.util.Arrays.asList("LBPA")),
    LCB(LipidCategory.SP, "Sphingoid base homologs and variants [SP0104]", 2, "1", "H", java.util.Arrays.asList("LCB", "Sphingosine", "So", "Sphinganine", "Sa", "SPH", "Sph")),
    LCBP(LipidCategory.SP, "Sphingoid base 1-phosphates [SP0105]", 2, "1", "H2O3P", java.util.Arrays.asList("LCBP", "Sphingosine-1-phosphate", "S1P", "SPH-P", "C1P", "SIP", "Sphinganine-1-phosphate", "Sa1P")),
    LCDPDAG(LipidCategory.GP, "Lyso-CDP-diacylglycerol", 2, "1", "", java.util.Arrays.asList("LCDPDAG")),
    LDMPE(LipidCategory.GP, "Lysodimethylphosphatidylethanolamine", 2, "1", "", java.util.Arrays.asList("LDMPE")),
    LEX_GM1(LipidCategory.SP, "Globoside", 2, "2", "C57H93N3O42", java.util.Arrays.asList("Lex-GM1")),
    LHEXCER(LipidCategory.SP, "Hexosylsphingosine", 2, "1", "C6H11O5", java.util.Arrays.asList("LHexCer", "HexSph")),
    LINOLEIC_ACID(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "C18H32O2", java.util.Arrays.asList("Linoleic acid")),
    LMMPE(LipidCategory.GP, "Lysomonomethylphosphatidylethanolamine", 2, "1", "C6H14NO6P", java.util.Arrays.asList("LMMPE")),
    LPA(LipidCategory.GP, "Monoacylglycerophosphates [GP1005]", 2, "1", "C3H7O6P", java.util.Arrays.asList("LPA", "LysoPA")),
    LPC(LipidCategory.GP, "Monoacylglycerophosphocholines [GP0105]", 2, "1", "C8H18NO6P", java.util.Arrays.asList("LPC", "LysoPC")),
    LPE(LipidCategory.GP, "Monoacylglycerophosphoethanolamines [GP0205]", 2, "1", "C5H12NO6P", java.util.Arrays.asList("LPE", "LysoPE")),
    LPG(LipidCategory.GP, "Monoacylglycerophosphoglycerols [GP0405]", 2, "1", "C6H13O8P", java.util.Arrays.asList("LPG", "LysoPG")),
    LPI(LipidCategory.GP, "Monoacylglycerophosphoinositols [GP0605]", 2, "1", "C9H17O11P", java.util.Arrays.asList("LPI", "LysoPI")),
    LPIM1(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C15H27O16P", java.util.Arrays.asList("LPIM1")),
    LPIM2(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C21H37O21P", java.util.Arrays.asList("LPIM2")),
    LPIM3(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C27H47O26P", java.util.Arrays.asList("LPIM3")),
    LPIM4(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C34H59O30P", java.util.Arrays.asList("LPIM4")),
    LPIM5(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C39H67O36P", java.util.Arrays.asList("LPIM5")),
    LPIM6(LipidCategory.GP, "Monoacylglycerophosphoinositolglycans [GP1504]", 2, "1", "C45H77O41P", java.util.Arrays.asList("LPIM6")),
    LPIMIP(LipidCategory.GP, "Lysophosphatidylinositol- mannosideinositolphosphate", 2, "1", "", java.util.Arrays.asList("LPIMIP")),
    LPIN(LipidCategory.GP, "Lysophosphatidylinositol-glucosamine", 2, "1", "", java.util.Arrays.asList("LPIN")),
    LPS(LipidCategory.GP, "Monoacylglycerophosphoserines [GP0305]", 2, "1", "C6H12NO8P", java.util.Arrays.asList("LPS", "LysoPS")),
    LSM(LipidCategory.SP, "Ceramides [SP02]", 2, "1", "C5H13NO3P", java.util.Arrays.asList("LSM", "SPC", "LysoSM")),
    LTB4(LipidCategory.FA, "Leukotrienes [FA0302]", 0, "0", "C20H32O4", java.util.Arrays.asList("LTB4")),
    LTC4(LipidCategory.FA, "Eicosanoid derivatives", 0, "0", "C30H47N3O9S", java.util.Arrays.asList("LTC4")),
    LTD4(LipidCategory.FA, "Leukotrienes [FA0302]", 0, "0", "C25H40N2O6S", java.util.Arrays.asList("LTD4")),
    M_IP_2C(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "C18H33O21P2", java.util.Arrays.asList("M(IP)2C")),
    MAG(LipidCategory.GL, "Monoacylglycerols [GL0101]", 3, "1", "C3H5O3", java.util.Arrays.asList("MAG", "MG")),
    MARESIN_1(LipidCategory.FA, "Maresins [FA0405]", 0, "0", "C22H32O4", java.util.Arrays.asList("Maresin 1")),
    MGDG(LipidCategory.GL, "Glycosyldiacylglycerols [GL0501]", 2, "2", "C9H16O8", java.util.Arrays.asList("MGDG")),
    MHDG(LipidCategory.GL, "Monohexosyldiacylglycerol", 2, "2", "C9H16O8", java.util.Arrays.asList("MHDG")),
    MIPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "C12H22O13P", java.util.Arrays.asList("MIPC")),
    MLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "3", "C9H18O13P2", java.util.Arrays.asList("MLCL")),
    MMPE(LipidCategory.GP, "Monomethylphosphatidylethanolamine", 2, "2|4", "C6H14NO6P", java.util.Arrays.asList("MMPE")),
    MSGG(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C43H70N2O33", java.util.Arrays.asList("MSGG")),
    NAE(LipidCategory.FA, "Fatty amides", 0, "0", "C2H6NO", java.util.Arrays.asList("NAE")),
    NAPE(LipidCategory.GP, "Diacylglycerophosphoethanolamines [GP0201]", 3, "3", "C5H11NO6P", java.util.Arrays.asList("NAPE")),
    NEUAC_ALPHA2_6_MSGG(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C54H86N3O41", java.util.Arrays.asList("NeuAc(alpha2-6)-MSGG")),
    NEUAC_ALPHA2_8_MSGG(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C54H86N3O41", java.util.Arrays.asList("NeuAc(alpha2-8)-MSGG")),
    NEUACGAL_IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C43H70N2O33", java.util.Arrays.asList("NeuAcGal-iGb4Cer")),
    NEUGC_GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C43H70N2O34", java.util.Arrays.asList("NeuGc-GalGb4Cer")),
    NEUGC_LACNAC_GM1_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C62H99N4O48", java.util.Arrays.asList("NeuGc-LacNAc-GM1(NeuGc)")),
    NEUGCNEUGC_GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C54H86N3O43", java.util.Arrays.asList("NeuGcNeuGc-GalGb4Cer")),
    NOR1(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C32H54NO25", java.util.Arrays.asList("NOR1")),
    NOR2(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C46H77N2O35", java.util.Arrays.asList("NOR2")),
    NORINT(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C40H67N2O30", java.util.Arrays.asList("NORint")),
    PA(LipidCategory.GP, "Glycerophosphates [GP10]", 2, "2", "C3H7O6P", java.util.Arrays.asList("PA")),
    PALMITIC_ACID(LipidCategory.FA, "Straight chain fatty acids [FA0101]", 0, "0", "C16H32O2", java.util.Arrays.asList("Palmitic acid")),
    PARA_FORSSMAN(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C34H57N2O25", java.util.Arrays.asList("Para-Forssman")),
    PAT16(LipidCategory.SL, "Acyltrehaloses [SL03]", 4, "4", "", java.util.Arrays.asList("PAT16")),
    PAT18(LipidCategory.SL, "Acyltrehaloses [SL03]", 4, "4", "", java.util.Arrays.asList("PAT18")),
    PC(LipidCategory.GP, "Glycerophosphocholines [GP01]", 2, "2", "C8H18NO6P", java.util.Arrays.asList("PC")),
    PE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "C5H12NO6P", java.util.Arrays.asList("PE")),
    PE_GLCDG(LipidCategory.GL, "Glycosylalkylacylglycerols [GL0502]", 2, "2", "C11H22NO11P", java.util.Arrays.asList("PE-GlcDG")),
    PE_NME(LipidCategory.GP, "Diacylglycerophosphoethanolamines [GP0201]", 2, "2", "C6H14NO6P", java.util.Arrays.asList("PE-NMe")),
    PE_NME2(LipidCategory.GP, "Diacylglycerophosphoethanolamines [GP0201]", 2, "2", "C7H16NO6P", java.util.Arrays.asList("PE-NMe2")),
    PET(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "C5H11O6P", java.util.Arrays.asList("PEt")),
    PG(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", 2, "2", "C6H13O8P", java.util.Arrays.asList("PG")),
    PGB2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H30O4", java.util.Arrays.asList("PGB2")),
    PGD2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H32O5", java.util.Arrays.asList("PGD2")),
    PGE2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H32O5", java.util.Arrays.asList("PGE2")),
    PGF2ALPHA(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H34O5", java.util.Arrays.asList("PGF2alpha")),
    PGI2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "C20H32O5", java.util.Arrays.asList("PGI2")),
    PGP(LipidCategory.GP, "Glycerophosphoglycerophosphates [GP05]", 2, "2", "C6H14O11P2", java.util.Arrays.asList("PGP")),
    PHENOL(LipidCategory.PK, "Alkyl phenols and derivatives [PK1501]", 2, "2", "", java.util.Arrays.asList("PHENOL")),
    PI(LipidCategory.GP, "Glycerophosphoinositols [GP06]", 2, "2", "C9H17O11P", java.util.Arrays.asList("PI")),
    PIM1(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C15H27O16P", java.util.Arrays.asList("PIM1")),
    PIM2(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C21H37O21P", java.util.Arrays.asList("PIM2")),
    PIM3(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C27H47O26P", java.util.Arrays.asList("PIM3")),
    PIM4(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C33H57O31P", java.util.Arrays.asList("PIM4")),
    PIM5(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C39H67O36P", java.util.Arrays.asList("PIM5")),
    PIM6(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C45H77O41P", java.util.Arrays.asList("PIM6")),
    PIMIP(LipidCategory.GP, "Phosphatidylinositol mannoside inositol phosphate", 2, "2", "", java.util.Arrays.asList("PIMIP")),
    PIP(LipidCategory.GP, "Diacylglycerophosphoinositol monophosphates [GP0701]", 2, "2", "C9H18O14P2", java.util.Arrays.asList("PIP")),
    PIP_3P(LipidCategory.GP, "Diacylglycerophosphoinositol monophosphates [GP0701]", 2, "2", "C9H18O14P2", java.util.Arrays.asList("PIP[3']", "PIP[3]")),
    PIP_4P(LipidCategory.GP, "Diacylglycerophosphoinositol monophosphates [GP0701]", 2, "2", "C9H18O14P2", java.util.Arrays.asList("PIP[4']", "PIP[4]")),
    PIP_5P(LipidCategory.GP, "Diacylglycerophosphoinositol monophosphates [GP0701]", 2, "2", "C9H18O14P2", java.util.Arrays.asList("PIP[5']", "PIP[5]")),
    PIP2(LipidCategory.GP, "Diacylglycerophosphoinositol bisphosphates [GP0801]", 2, "2", "C9H19O17P3", java.util.Arrays.asList("PIP2")),
    PIP2_3P_4P(LipidCategory.GP, "Diacylglycerophosphoinositol bisphosphates [GP0801]", 2, "2", "C9H19O17P3", java.util.Arrays.asList("PIP2[3',4']", "PIP2[3,4]")),
    PIP2_3P_5P(LipidCategory.GP, "Diacylglycerophosphoinositol bisphosphates [GP0801]", 2, "2", "C9H19O17P3", java.util.Arrays.asList("PIP2[3',5']", "PIP2[3,5]")),
    PIP2_4P_5P(LipidCategory.GP, "Diacylglycerophosphoinositol bisphosphates [GP0801]", 2, "2", "C9H19O17P3", java.util.Arrays.asList("PIP2[4',5']", "PIP2[4,5]")),
    PIP3(LipidCategory.GP, "Diacylglycerophosphoinositol trisphosphates [GP0901]", 2, "2", "C9H20O20P4", java.util.Arrays.asList("PIP3")),
    PIP3_3P_4P_5P(LipidCategory.GP, "Diacylglycerophosphoinositol trisphosphates [GP0901]", 2, "2", "C9H20O20P4", java.util.Arrays.asList("PIP3[3',4',5']", "PIP3[3,4,5]")),
    PNC(LipidCategory.GP, "Glycerophosphonocholines [GP16]", 2, "2", "C8H18NO5P", java.util.Arrays.asList("PnC")),
    PNE(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "C5H12NO5P", java.util.Arrays.asList("PnE")),
    PPA(LipidCategory.GP, "Diacylglyceropyrophosphates [GP1101]", 2, "2", "C3H8O9P2", java.util.Arrays.asList("PPA")),
    PS(LipidCategory.GP, "Glycerophosphoserines [GP03]", 2, "2", "C6H12NO8P", java.util.Arrays.asList("PS")),
    PS_NAC(LipidCategory.GP, "Diacylglycerophosphoserines [GP0301]", 3, "3", "C6H11NO8P", java.util.Arrays.asList("PS-NAc")),
    PT(LipidCategory.GP, "Other Glycerophospholipids [GP00]", 2, "2", "C7H14NO8P", java.util.Arrays.asList("PT")),
    RESOLVIN_D1(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "C22H32O5", java.util.Arrays.asList("Resolvin D1")),
    RESOLVIN_D2(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "C22H32O5", java.util.Arrays.asList("Resolvin D2")),
    RESOLVIN_D3(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "C22H32O5", java.util.Arrays.asList("Resolvin D3")),
    RESOLVIN_D5(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "C22H32O4", java.util.Arrays.asList("Resolvin D5")),
    RESORCINOL(LipidCategory.PK, "Alkyl resorcinols and derivatives [PK1503]", 2, "2", "", java.util.Arrays.asList("RESORCINOL")),
    SB1A(LipidCategory.SP, "Globoside", 2, "2", "C26H42NO26S2", java.util.Arrays.asList("SB1a")),
    SE_27_1(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C27H45O", java.util.Arrays.asList("SE 27:1", "ChE", "CE", "Cholesteryl ester", "Cholesterol ester", "SE", "Sterol ester")),
    SE_27_2(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C27H43O", java.util.Arrays.asList("SE 27:2", "Desmosterol ester")),
    SE_28_2(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C28H45O", java.util.Arrays.asList("SE 28:2", "Ergostadienol ester")),
    SE_28_3(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C28H43O", java.util.Arrays.asList("SE 28:3", "Ergosterol ester")),
    SE_29_2(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C29H47O", java.util.Arrays.asList("SE 29:2", "Stigmasterol ester")),
    SE_30_2(LipidCategory.ST, "Sterol esters [ST0102]", 1, "1", "C30H49O", java.util.Arrays.asList("SE 30:2", "Lanosterol ester")),
    SHEX2CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C12H19O14S", java.util.Arrays.asList("SHex2Cer", "SulfoHex2Cer")),
    SHEXCER(LipidCategory.SP, "Sulfoglycosphingolipids (sulfatides) [SP0602]", 2, "2", "C6H11O8S", java.util.Arrays.asList("SHexCer", "SulfoHexCer", "(3'-sulfo)Galbeta-Cer", "(3'-sulfo)GalCer")),
    SLBPA(LipidCategory.GP, "Diacylglycerophosphomonoradylglycerols [GP0409]", 3, "3", "C6H12O8P", java.util.Arrays.asList("SLBPA")),
    SM(LipidCategory.SP, "Ceramide phosphocholines (sphingomyelins) [SP0301]", 2, "2", "C5H13NO3P", java.util.Arrays.asList("SM")),
    SM1A(LipidCategory.SP, "Globoside", 2, "2", "C26H43NO23S", java.util.Arrays.asList("SM1a")),
    SM1B(LipidCategory.SP, "Globoside", 2, "2", "C26H43NO23S", java.util.Arrays.asList("SM1b")),
    SO3_GAL_IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C34H56N2O28S", java.util.Arrays.asList("SO3-Gal-iGb4Cer")),
    SO3_GALGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C32H53NO28S", java.util.Arrays.asList("SO3-GalGb4Cer")),
    SO3_GB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H43NO23S", java.util.Arrays.asList("SO3-Gb4Cer")),
    SO3_GM1_NEUGC(LipidCategory.SP, "Globoside", 2, "2", "C37H59N2O32S", java.util.Arrays.asList("SO3-GM1(NeuGc)")),
    SO3_IGB4CER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C26H43NO23S", java.util.Arrays.asList("SO3-iGb4Cer")),
    SQDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "C9H16O10S", java.util.Arrays.asList("SQDG")),
    SQMG(LipidCategory.GL, "Glycosylmonoacylglycerols [GL0401]", 2, "1", "C9H16O10S", java.util.Arrays.asList("SQMG")),
    ST_27_1_1(LipidCategory.ST, "Cholesterol and derivatives [ST0101]", 0, "0", "C27H46O", java.util.Arrays.asList("ST 27:1;1", "CH", "FC", "Cholesterol", "Ch", "ST")),
    ST_27_2_1(LipidCategory.ST, "Cholesterol and derivatives [ST0101]", 0, "0", "C27H44O", java.util.Arrays.asList("ST 27:2;1", "Desmosterol")),
    ST_28_2_1(LipidCategory.ST, "Ergosterols and C24-methyl derivatives [ST0103]", 0, "0", "C28H46O", java.util.Arrays.asList("ST 28:2;1", "Ergostadienol")),
    ST_28_3_1(LipidCategory.ST, "Ergosterols and C24-methyl derivatives [ST0103]", 0, "0", "C28H44O", java.util.Arrays.asList("ST 28:3;1", "Ergosterol")),
    ST_29_2_1(LipidCategory.ST, "Stigmasterols and C24-ethyl derivatives [ST0104]", 0, "0", "C29H48O", java.util.Arrays.asList("ST 29:2;1", "Stigmasterol")),
    ST_30_2_1(LipidCategory.ST, "Cholesterol and derivatives [ST0101]", 0, "0", "C30H50O", java.util.Arrays.asList("ST 30:2;1", "Lanosterol")),
    SULFOGALCER(LipidCategory.SP, "Glycosphingolipids", 2, "2", "C6H11O8S", java.util.Arrays.asList("SulfoGalCer")),
    TAG(LipidCategory.GL, "Triacylglycerols [GL0301]", 3, "3", "C3H5O3", java.util.Arrays.asList("TAG", "TG")),
    TETRANOR_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "C16H26O3", java.util.Arrays.asList("tetranor-12-HETE")),
    TXB1(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "C20H36O6", java.util.Arrays.asList("TXB1")),
    TXB2(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "C20H34O6", java.util.Arrays.asList("TXB2")),
    TXB3(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "C20H32O6", java.util.Arrays.asList("TXB3")),
    UNDEFINED(LipidCategory.UNDEFINED, "Undefined lipid class", 0, "0", "", java.util.Arrays.asList("UNDEFINED")),
    WE(LipidCategory.FA, "Fatty esters [FA07]", 2, "2", "", java.util.Arrays.asList("WE"));

    private final LipidCategory category;

    private final String lipidMapsClassName;

    private final String allowedNumFaStr;

    private final List<Integer> allowedNumFa;

    private final Integer maxNumFa;

    private final String sumFormula;

    private final ElementTable elementTable;

    private final List<String> synonyms;

    private LipidClass(LipidCategory category, String lipidMapsClassName, Integer maxNumFa,
            String allowedNumFaStr, String sumFormula, List<String> synonyms) {
        this.category = category;
        this.lipidMapsClassName = lipidMapsClassName;
        this.maxNumFa = maxNumFa;
        this.allowedNumFaStr = allowedNumFaStr;
        this.sumFormula = sumFormula;
        ElementTable et = new ElementTable();
        if (this.sumFormula != null && !this.sumFormula.isEmpty()) {
            try {
                et = new ElementTable(this.sumFormula);
            } catch (de.isas.lipidomics.palinom.exceptions.ParsingException ex) {
                et = new ElementTable();
            }
        }
        this.elementTable = et;;
        if (synonyms.isEmpty()) {
            throw new IllegalArgumentException("Must supply at least one synonym!");
        };
        this.allowedNumFa = Arrays.asList(allowedNumFaStr.split("\\|")).stream().map((t) -> {
            return Integer.parseInt(t);
        }).collect(java.util.stream.Collectors.toList());
        this.synonyms = synonyms;
    }

    public LipidCategory getCategory() {
        return this.category;
    }

    public String getAbbreviation() {
        return this.synonyms.get(0);
    }

    public String getLipidMapsClassName() {
        return this.lipidMapsClassName;
    }

    public Integer getMaxNumFa() {
        return this.maxNumFa;
    }

    public List<Integer> getAllowedNumFa() {
        return this.allowedNumFa;
    }

    public String getSumFormula() {
        return this.elementTable.getSumFormula();
    }

    public ElementTable getElements() {
        return this.elementTable.copy();
    }

    public List<String> getSynonyms() {
        return this.synonyms;
    }

    public boolean matchesAbbreviation(String headGroup) {
        return this.synonyms.stream().anyMatch((synonym) -> {
            return synonym.equals(headGroup);
        });
    }

    public String getLysoAbbreviation(LipidClass lipidClass) {
        if (lipidClass.getCategory() == LipidCategory.GP) {
            return "L" + lipidClass.getAbbreviation();
        }
        throw new ConstraintViolationException("Lipid category must be " + LipidCategory.GP + " for lyso-classes!");
    }

    public static Optional<LipidClass> forHeadGroup(String headGroup) {
        return Arrays.asList(values()).stream().filter((lipidClass) -> {
            return lipidClass.matchesAbbreviation(headGroup.trim());
        }).findFirst();
    }
}
