//  Copyright 2019 nils.hoffmann.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
package de.isas.lipidomics.domain;

import de.isas.lipidomics.palinom.exceptions.ConstraintViolationException;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

/**
 * This class was generated by the LipidClassGenerator.
 *
 * Enumeration of lipid classes. The shorthand names / abbreviations are used to
 * look up the lipid class association of a lipid head group. We try to map each
 * abbreviation and synonyms thereof to LipidMAPS main class. However, not all
 * described head groups are categorized in LipidMAPS, or only occur in other
 * databases, so they do not have such an association at the moment.
 *
 * Example: Category=Glyerophospholipids -> Class=Glycerophosphoinositols (PI)
 *
 * @author nils.hoffmann
 */
public enum LipidClass {
    UNDEFINED(LipidCategory.UNDEFINED, "Undefined lipid class", 0, "0", "UNDEFINED"),
    FA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "FA"),
    FA_10_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "10-HDoHE"),
    FA_11_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "11-HDoHE"),
    FA_11_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "11-HETE"),
    FA_11_12_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "11,12-DHET", "11,12-DiHETrE"),
    FA_11_12_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "11(12)-EET", "11,12-EpETrE"),
    FA_12_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "12-HEPE"),
    FA_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "12-HETE"),
    FA_12_HHTRE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatrienoic acids [FA0305]", 0, "0", "12-HHTrE"),
    FA_12_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "12-OxoETE"),
    FA_12_13_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "12(13)-EpOME"),
    FA_13_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "13-HODE"),
    FA_13_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "13-HOTrE"),
    FA_14_15_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "14,15-DHET", "14,15-DiHETrE"),
    FA_14_15_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "14(15)-EET", "14,15-EpETrE"),
    FA_14_15_EPETE(LipidCategory.FA, "Other Eicosanoids [FA0300]", 0, "0", "14(15)-EpETE"),
    FA_15_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "15-HEPE"),
    FA_15_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "15-HETE"),
    FA_15D_PGJ2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "15d-PGJ2"),
    FA_16_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "16-HDoHE"),
    FA_16_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "16-HETE"),
    FA_18_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "18-HEPE"),
    FA_5_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "5-HEPE"),
    FA_5_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "5-HETE"),
    FA_5_HPETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "5-HpETE"),
    FA_5_OXOETE(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "5-OxoETE"),
    FA_5_12_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "5,12-DiHETE"),
    FA_5_6_DIHETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "5,6-DiHETE"),
    FA_5_6_15_LXA4(LipidCategory.FA, "Lipoxins [FA0304]", 0, "0", "5,6,15-LXA4"),
    FA_5_6_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "5(6)-EET", "5,6-EpETrE"),
    FA_8_HDOHE(LipidCategory.FA, "Other Docosanoids [FA0400]", 0, "0", "8-HDoHE"),
    FA_8_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "8-HETE"),
    FA_8_9_DHET(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "8,9-DHET", "8,9-DiHETrE"),
    FA_8_9_EET(LipidCategory.FA, "Epoxyeicosatrienoic acids [FA0308]", 0, "0", "8(9)-EET", "8,9-EpETrE"),
    FA_9_HEPE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosapentaenoic acids [FA0307]", 0, "0", "9-HEPE"),
    FA_9_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "9-HETE"),
    FA_9_HODE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "9-HODE"),
    FA_9_HOTRE(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "9-HOTrE"),
    FA_9_10_EPOME(LipidCategory.FA, "Other Octadecanoids [FA0200]", 0, "0", "9(10)-EpOME"),
    AA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "AA", "Arachidonic acid", "Arachidonic Acid"),
    ALPHA_LA(LipidCategory.FA, "Fatty acids and conjugates [FA01]", 0, "0", "alpha-LA", "ALA"),
    DHA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "DHA", "Docosapentaenoic acid"),
    EPA(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "EPA", "Eicosapentaenoic acid"),
    GP_NAE(LipidCategory.FA, "X-ethanolamine", 0, "0", "GP-NAE"),
    LINOLEIC_ACID(LipidCategory.FA, "Unsaturated fatty acids [FA0103]", 0, "0", "Linoleic acid"),
    LTB4(LipidCategory.FA, "Leukotrienes [FA0302]", 0, "0", "LTB4"),
    LTC4(LipidCategory.FA, "Leukotrienes [FA0302]", 0, "0", "LTC4"),
    LTD4(LipidCategory.FA, "Leukotrienes [FA0302]", 0, "0", "LTD4"),
    MARESIN_1(LipidCategory.FA, "Maresins [FA0405]", 0, "0", "Maresin 1"),
    NAE(LipidCategory.FA, "X-ethanolamine", 0, "0", "NAE"),
    PALMITIC_ACID(LipidCategory.FA, "Straight chain fatty acids [FA0101]", 0, "0", "Palmitic acid"),
    PGB2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "PGB2"),
    PGD2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "PGD2"),
    PGE2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "PGE2"),
    PGF2ALPHA(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "PGF2alpha"),
    PGI2(LipidCategory.FA, "Prostaglandins [FA0301]", 0, "0", "PGI2"),
    RESOLVIN_D1(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "Resolvin D1"),
    RESOLVIN_D2(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "Resolvin D2"),
    RESOLVIN_D3(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "Resolvin D3"),
    RESOLVIN_D5(LipidCategory.FA, "Resolvin Ds [FA0403]", 0, "0", "Resolvin D5"),
    TETRANOR_12_HETE(LipidCategory.FA, "Hydroxy/hydroperoxyeicosatetraenoic acids [FA0306]", 0, "0", "tetranor-12-HETE"),
    TXB1(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "TXB1"),
    TXB2(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "TXB2"),
    TXB3(LipidCategory.FA, "Thromboxanes [FA0303]", 0, "0", "TXB3"),
    COA(LipidCategory.FA, "Fatty acyl CoAs [FA0705]", 0, "0", "CoA"),
    FAHFA(LipidCategory.FA, "Wax monoesters [FA0701]", 0, "0", "FAHFA"),
    DAG(LipidCategory.GL, "Diradylglycerols [GL02]", 3, "2", "DAG", "DG"),
    DGDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "DGDG"),
    DHDG(LipidCategory.GL, "Dihexosyldiacylglycerol", 2, "2", "DHDG"),
    MAG(LipidCategory.GL, "Monoradylglycerols [GL01]", 3, "1", "MAG", "MG"),
    MGDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "MGDG"),
    MHDG(LipidCategory.GL, "Monohexosyldiacylglycerol", 2, "2", "MHDG"),
    SQDG(LipidCategory.GL, "Glycosyldiradylglycerols [GL05]", 2, "2", "SQDG"),
    SQMG(LipidCategory.GL, "Glycosylmonoradylglycerols [GL04]", 2, "1", "SQMG"),
    TAG(LipidCategory.GL, "Triradylglycerols [GL03]", 3, "3", "TAG", "TG"),
    GP_6_AC_GLC_GP(LipidCategory.GP, "Glycosylglycerophospholipids [GP14]", 2, "2", "6-Ac-Glc-GP"),
    BMP(LipidCategory.GP, "Monoacylglycerophosphomonoradylglycerols [GP0410]", 4, "2|4", "BMP", "LBPA"),
    CDPDAG(LipidCategory.GP, "CDP-Glycerols [GP13]", 2, "2", "CDPDAG", "CDPDG", "CDP-DG", "CDP-DAG"),
    CL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "4", "CL"),
    CPA(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 1, "1", "CPA"),
    DLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "2", "DLCL"),
    DMPE(LipidCategory.GP, "Dimethylphosphatidylethanolamine", 2, "2", "DMPE"),
    GLC_DG(LipidCategory.GP, "Glycosyldiradylglycerols [GL05]", 2, "2", "Glc-DG"),
    GLC_GP(LipidCategory.GP, "Glycosylglycerophospholipids [GP14]", 2, "2", "Glc-GP"),
    LCDPDAG(LipidCategory.GP, "Lyso-CDP-diacylglycerol", 2, "1", "LCDPDAG"),
    LDMPE(LipidCategory.GP, "Lysodimethylphosphatidylethanolamine", 2, "1", "LDMPE"),
    LMMPE(LipidCategory.GP, "Lysomonomethylphosphatidylethanolamine", 2, "1", "LMMPE"),
    LPA(LipidCategory.GP, "Glycerophosphates [GP10]", 2, "1", "LPA", "LysoPA"),
    LPC(LipidCategory.GP, "Glycerophosphocholines [GP01]", 2, "1", "LPC", "LysoPC"),
    LPE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "1", "LPE", "LysoPE"),
    LPG(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", 2, "1", "LPG", "LysoPG"),
    LPI(LipidCategory.GP, "Glycerophosphoinositols [GP06]", 2, "1", "LPI", "LysoPI"),
    LPIM1(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM1"),
    LPIM2(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM2"),
    LPIM3(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM3"),
    LPIM4(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM4"),
    LPIM5(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM5"),
    LPIM6(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "1", "LPIM6"),
    LPIMIP(LipidCategory.GP, "Lysophosphatidylinositol- mannosideinositolphosphate", 2, "1", "LPIMIP"),
    LPIN(LipidCategory.GP, "Lysophosphatidylinositol-glucosamine", 2, "1", "LPIN"),
    LPS(LipidCategory.GP, "Glycerophosphoserines [GP03]", 2, "1", "LPS", "LysoPS"),
    MLCL(LipidCategory.GP, "Glycerophosphoglycerophosphoglycerols [GP12]", 4, "3", "MLCL"),
    NAPE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 3, "3", "NAPE"),
    PA(LipidCategory.GP, "Glycerophosphates [GP10]", 2, "2", "PA"),
    PC(LipidCategory.GP, "Glycerophosphocholines [GP01]", 2, "2", "PC"),
    PE(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "PE"),
    PE_NME(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "PE-NMe"),
    PE_NME2(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "PE-NMe2"),
    PET(LipidCategory.GP, "Glycerophosphoethanolamines [GP02]", 2, "2", "PEt"),
    PG(LipidCategory.GP, "Glycerophosphoglycerols [GP04]", 2, "2", "PG"),
    PGP(LipidCategory.GP, "Glycerophosphoglycerophosphates [GP05]", 2, "2", "PGP"),
    PI(LipidCategory.GP, "Glycerophosphoinositols [GP06]", 2, "2", "PI"),
    PIM1(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM1"),
    PIM2(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM2"),
    PIM3(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM3"),
    PIM4(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM4"),
    PIM5(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM5"),
    PIM6(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PIM6"),
    PIMIP(LipidCategory.GP, "Phosphatidylinositol mannoside inositol phosphate", 2, "2", "PIMIP"),
    PIP(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", 2, "2", "PIP"),
    PIP_3P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", 2, "2", "PIP[3']", "PIP[3]"),
    PIP_4P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", 2, "2", "PIP[4']", "PIP[4]"),
    PIP_5P_(LipidCategory.GP, "Glycerophosphoinositol monophosphates [GP07]", 2, "2", "PIP[5']", "PIP[5]"),
    PIP2(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", 2, "2", "PIP2"),
    PIP2_3P_4P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", 2, "2", "PIP2[3',4']", "PIP2[3,4]"),
    PIP2_3P_5P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", 2, "2", "PIP2[3',5']", "PIP2[3,5]"),
    PIP2_4P_5P_(LipidCategory.GP, "Glycerophosphoinositol bisphosphates [GP08]", 2, "2", "PIP2[4',5']", "PIP2[4,5]"),
    PIP3(LipidCategory.GP, "Glycerophosphoinositol trisphosphates [GP09]", 2, "2", "PIP3"),
    PIP3_3P_4P_5P_(LipidCategory.GP, "Glycerophosphoinositol trisphosphates [GP09]", 2, "2", "PIP3[3',4',5']", "PIP3[3,4,5]"),
    PNC(LipidCategory.GP, "Glycerophosphonocholines [GP16]", 2, "2", "PnC"),
    PNE(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PnE"),
    PPA(LipidCategory.GP, "Diacylglyceropyrophosphates [GP1101]", 2, "2", "PPA"),
    PS(LipidCategory.GP, "Glycerophosphoserines [GP03]", 2, "2", "PS"),
    PT(LipidCategory.GP, "Glycerophosphoinositolglycans [GP15]", 2, "2", "PT"),
    AC2SGL(LipidCategory.SL, "Acyltrehaloses [SL03]", 2, "2", "AC2SGL"),
    DAT(LipidCategory.SL, "Acyltrehaloses [SL03]", 2, "2", "DAT"),
    PAT16(LipidCategory.SL, "Acyltrehaloses [SL03]", 4, "4", "PAT16"),
    PAT18(LipidCategory.SL, "Acyltrehaloses [SL03]", 4, "4", "PAT18"),
    SP_3P_SULFO_LACCER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "(3'-sulfo)LacCer"),
    SP_FUC_IGB3CER(LipidCategory.SP, "Globoside", 2, "2", "(Fuc)iGb3Cer"),
    AC_O_9_GD1A(LipidCategory.SP, "Globoside", 2, "2", "Ac-O-9-GD1a"),
    AC_O_9_GT1B(LipidCategory.SP, "Globoside", 2, "2", "Ac-O-9-GT1b"),
    AC_O_9_GT3(LipidCategory.SP, "Globoside", 2, "2", "Ac-O-9-GT3"),
    BRANCHED_FORSSMAN(LipidCategory.SP, "Globoside", 2, "2", "Branched-Forssman"),
    C1P(LipidCategory.SP, "Ceramide-1-phosphates [SP0205]", 2, "2", "C1P"),
    CER(LipidCategory.SP, "Ceramides [SP02]", 2, "2", "Cer", "Ceramide"),
    CERP(LipidCategory.SP, "Ceramides [SP02]", 2, "2", "CerP"),
    DSGG(LipidCategory.SP, "Globoside", 2, "2", "DSGG"),
    EPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "EPC", "PE-Cer"),
    FMC_5(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "FMC-5"),
    FMC_6(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "FMC-6"),
    FORSSMAN(LipidCategory.SP, "Globoside", 2, "2", "Forssman"),
    FUC_BRANCHED_FORSSMAN(LipidCategory.SP, "Globoside", 2, "2", "Fuc-Branched-Forssman"),
    FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "Fuc-GA1"),
    FUC_GD1B(LipidCategory.SP, "Globoside", 2, "2", "Fuc-GD1b"),
    FUC_GM1(LipidCategory.SP, "Globoside", 2, "2", "Fuc-GM1"),
    FUC_GM1_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "Fuc-GM1(NeuGc)"),
    FUC_IGB3CER(LipidCategory.SP, "Globoside", 2, "2", "Fuc-iGb3Cer"),
    FUC_GAL_GM1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "Fuc(Gal)-GM1"),
    FUC_GAL_GAL_IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "Fuc(Gal)Gal-iGb4Cer"),
    FUCGALGB3CER(LipidCategory.SP, "Globoside", 2, "2", "FucGalGb3Cer"),
    GA1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GA1"),
    GA2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GA2"),
    GAL_GD1B(LipidCategory.SP, "Globoside", 2, "2", "Gal-GD1b"),
    GAL_IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "Gal-iGb4Cer"),
    GAL_FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "Gal(Fuc)-GA1"),
    GAL_FUC_GD1B(LipidCategory.SP, "Globoside", 2, "2", "Gal(Fuc)-GD1b"),
    GALGAL_GD1B(LipidCategory.SP, "Globoside", 2, "2", "GalGal-GD1b"),
    GALGALGALGB3CER(LipidCategory.SP, "Globoside", 2, "2", "GalGalGalGb3Cer"),
    GALGALGB3CER(LipidCategory.SP, "Globoside", 2, "2", "GalGalGb3Cer"),
    GALGALNAC_GM1B_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GalGalNAc-GM1b(NeuGc)"),
    GALGB3CER(LipidCategory.SP, "Globoside", 2, "2", "GalGb3Cer"),
    GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "GalGb4Cer"),
    GALGLCNAC_GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "GalGlcNAc-GalGb4Cer"),
    GALNAC_GD1A(LipidCategory.SP, "Globoside", 2, "2", "GalNAc-GD1a"),
    GALNAC_GD1A_NEUGC_NEUAC_(LipidCategory.SP, "Globoside", 2, "2", "GalNAc-GD1a(NeuGc/NeuAc)"),
    GALNAC_GM1(LipidCategory.SP, "Globoside", 2, "2", "GalNAc-GM1"),
    GALNAC_GM1B(LipidCategory.SP, "Globoside", 2, "2", "GalNAc-GM1b"),
    GALNAC_GM1B_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GalNAc-GM1b(NeuGc)"),
    GALNACGAL_FUC_GA1(LipidCategory.SP, "Globoside", 2, "2", "GalNAcGal(Fuc)-GA1"),
    GALNACGALGB3CER(LipidCategory.SP, "Globoside", 2, "2", "GalNAcGalGb3Cer"),
    GB3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "Gb3"),
    GB3CER(LipidCategory.SP, "Globoside", 2, "2", "Gb3Cer"),
    GB4(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "GB4"),
    GB4CER(LipidCategory.SP, "Globoside", 2, "2", "Gb4Cer", "Tetrahexosylceramide"),
    GD1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD1"),
    GD1A(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD1a"),
    GD1A_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids", 2, "2", "GD1a alpha"),
    GD1A_NEUAC_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GD1a(NeuAc/NeuGc)"),
    GD1A_NEUGC_NEUAC_(LipidCategory.SP, "Globoside", 2, "2", "GD1a(NeuGc/NeuAc)"),
    GD1A_NEUGC_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GD1a(NeuGc/NeuGc)"),
    GD1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD1b"),
    GD1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD1c"),
    GD1C_NEUGC_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GD1c(NeuGc/NeuGc)"),
    GD2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD2"),
    GD3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GD3"),
    GLCNAC_GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "GlcNAc-GalGb4Cer"),
    GLCNACGB3CER(LipidCategory.SP, "Globoside", 2, "2", "GlcNAcGb3Cer"),
    GLOBO_A(LipidCategory.SP, "Globoside", 2, "2", "Globo-A"),
    GLOBO_B(LipidCategory.SP, "Globoside", 2, "2", "Globo-B"),
    GLOBO_H(LipidCategory.SP, "Globoside", 2, "2", "Globo-H"),
    GLOBO_LEX_9(LipidCategory.SP, "Globoside", 2, "2", "Globo-Lex-9"),
    GM1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GM1"),
    GM1_ALPHA(LipidCategory.SP, "Globoside", 2, "2", "GM1 alpha"),
    GM1_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GM1(NeuGc)"),
    GM1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GM1b"),
    GM1B_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GM1b(NeuGc)"),
    GM2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GM2"),
    GM2_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GM2(NeuGc)"),
    GM3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GM3"),
    GM4(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GM4"),
    GP1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GP1"),
    GP1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GP1c"),
    GP1C_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GP1c alpha"),
    GQ1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GQ1"),
    GQ1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GQ1b"),
    GQ1B_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GQ1b alpha"),
    GQ1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GQ1c"),
    GT1(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT1"),
    GT1A(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT1a"),
    GT1A_ALPHA(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT1a alpha"),
    GT1B(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT1b"),
    GT1B_ALPHA(LipidCategory.SP, "Globoside", 2, "2", "GT1b alpha"),
    GT1B_ALPHA_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "GT1b alpha(NeuGc)"),
    GT1C(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT1c"),
    GT2(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT2"),
    GT3(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "GT3"),
    HEX2CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "Hex2Cer", "LacCer"),
    HEX3CER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "Hex3Cer", "GB3"),
    HEXCER(LipidCategory.SP, "Neutral glycosphingolipids [SP05]", 2, "2", "HexCer", "GalCer", "GlcCer", "Glucosylceramide"),
    I_FORSSMAN(LipidCategory.SP, "Globoside", 2, "2", "i-Forssman"),
    IGB3CER(LipidCategory.SP, "Globoside", 2, "2", "iGb3Cer"),
    IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "iGb4Cer"),
    IPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "IPC", "PI-Cer"),
    LCB(LipidCategory.SP, "Sphingoid bases [SP01]", 2, "1", "LCB", "Sphingosine", "So", "Sphinganine", "Sa", "SPH", "Sph"),
    LCBP(LipidCategory.SP, "Sphingoid bases [SP01]", 2, "1", "LCBP", "Sphingosine-1-phosphate", "S1P", "SPH-P", "C1P", "SIP", "Sphinganine-1-phosphate", "Sa1P"),
    LEX_GM1(LipidCategory.SP, "Globoside", 2, "2", "Lex-GM1"),
    LHEXCER(LipidCategory.SP, "Hexosylsphingosine", 2, "1", "LHexCer", "HexSph"),
    LSM(LipidCategory.SP, "Ceramides [SP02]", 2, "1", "LSM", "SPC", "LysoSM"),
    M_IP_2C(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "M(IP)2C"),
    MIPC(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "MIPC"),
    MSGG(LipidCategory.SP, "Globoside", 2, "2", "MSGG"),
    NEUAC_ALPHA2_6_MSGG(LipidCategory.SP, "Globoside", 2, "2", "NeuAc(alpha2-6)-MSGG"),
    NEUAC_ALPHA2_8_MSGG(LipidCategory.SP, "Globoside", 2, "2", "NeuAc(alpha2-8)-MSGG"),
    NEUACGAL_IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "NeuAcGal-iGb4Cer"),
    NEUGC_GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "NeuGc-GalGb4Cer"),
    NEUGC_LACNAC_GM1_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "NeuGc-LacNAc-GM1(NeuGc)"),
    NEUGCNEUGC_GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "NeuGcNeuGc-GalGb4Cer"),
    NOR1(LipidCategory.SP, "Globoside", 2, "2", "NOR1"),
    NOR2(LipidCategory.SP, "Globoside", 2, "2", "NOR2"),
    NORINT(LipidCategory.SP, "Globoside", 2, "2", "NORint"),
    PARA_FORSSMAN(LipidCategory.SP, "Globoside", 2, "2", "Para-Forssman"),
    SB1A(LipidCategory.SP, "Globoside", 2, "2", "SB1a"),
    SHEX2CER(LipidCategory.SP, "Sulfodihexosyl ceramide", 2, "2", "SHex2Cer", "SulfoHex2Cer"),
    SHEXCER(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "SHexCer", "SulfoHexCer", "(3'-sulfo)Galbeta-Cer", "(3'-sulfo)GalCer"),
    SM(LipidCategory.SP, "Phosphosphingolipids [SP03]", 2, "2", "SM"),
    SM1A(LipidCategory.SP, "Globoside", 2, "2", "SM1a"),
    SM1B(LipidCategory.SP, "Globoside", 2, "2", "SM1b"),
    SO3_GAL_IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "SO3-Gal-iGb4Cer"),
    SO3_GALGB4CER(LipidCategory.SP, "Globoside", 2, "2", "SO3-GalGb4Cer"),
    SO3_GB4CER(LipidCategory.SP, "Globoside", 2, "2", "SO3-Gb4Cer"),
    SO3_GM1_NEUGC_(LipidCategory.SP, "Globoside", 2, "2", "SO3-GM1(NeuGc)"),
    SO3_IGB4CER(LipidCategory.SP, "Globoside", 2, "2", "SO3-iGb4Cer"),
    SULFOGALCER(LipidCategory.SP, "Acidic glycosphingolipids [SP06]", 2, "2", "SulfoGalCer"),
    SE(LipidCategory.ST, "Steryl esters [ST0102]", 1, "1", "SE"),
    ST(LipidCategory.ST, "Sterols [ST01]", 0, "0", "ST"),
    ST_27_1_1(LipidCategory.ST, "Cholesterol [LMST01010001]", 0, "0", "ST 27:1;1", "CH", "FC", "Cholesterol"),
    SE_27_1(LipidCategory.ST, "Cholesteryl esters [ST0102]", 1, "1", "SE 27:1", "ChE", "CE", "Cholesteryl ester", "Cholesterol ester"),
    ST_27_2_1(LipidCategory.ST, "Desmosterol", 0, "0", "ST 27:2;1"),
    SE_27_2(LipidCategory.ST, "Desmosterol Ester", 1, "1", "SE 27:2"),
    ST_29_2_1(LipidCategory.ST, "Stigmasterol", 0, "0", "ST 29:2;1"),
    SE_29_2(LipidCategory.ST, "Stigmasterol Ester", 1, "1", "SE 29:2"),
    ST_28_3_1(LipidCategory.ST, "Ergosterol", 0, "0", "ST 28:3;1"),
    SE_28_3(LipidCategory.ST, "Ergosterol Ester", 1, "1", "SE 28:3"),
    ST_30_2_1(LipidCategory.ST, "Lanosterol", 0, "0", "ST 30:2;1"),
    SE_30_2(LipidCategory.ST, "Lanosterol Ester", 1, "1", "SE 30:2"),
    ST_28_2_1(LipidCategory.ST, "Ergostadienol", 0, "0", "ST 28:2;1"),
    SE_28_2(LipidCategory.ST, "Ergostadienol Ester", 1, "1", "SE 28:2"),
    WE(LipidCategory.FA, "Fatty esters [FA07]", 0, "0", "WE"),
    RESORCINOL(LipidCategory.PK, "Alkyl resorcinols and derivatives [PK1503]", 2, "2", "RESORCINOL"),
    ANACARD(LipidCategory.PK, "Anacardic acids and derivatives [PK1504]", 2, "2", "ANACARD"),
    PHENOL(LipidCategory.PK, "Alkyl phenols and derivatives [PK1501]", 2, "2", "PHENOL"),
    CATECHOL(LipidCategory.PK, "Alkyl catechols and derivatives [PK1502]", 2, "2", "CATECHOL"),
    CAR(LipidCategory.FA, "Fatty acyl carnitines [FA0707]", 2, "2", "CAR"),
    DGCC(LipidCategory.GL, "Other Glycerolipids [GL00]", 2, "2", "DGCC"),
    PS_NAC(LipidCategory.GP, "Diacylglycerophosphoserines [GP0301]", 2, "2", "PS-NAc"),
    SLBPA(LipidCategory.GP, "Diacylglycerophosphomonoradylglycerols [GP0409]", 3, "3", "SLBPA"),
    SP_1_O_MYRISTOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-myristoyl-Cer"),
    SP_1_O_PALMITOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-palmitoyl-Cer"),
    SP_1_O_STEAROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-stearoyl-Cer"),
    SP_1_O_EICOSANOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-eicosanoyl-Cer"),
    SP_1_O_BEHENOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-behenoyl-Cer"),
    SP_1_O_LIGNOCEROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-lignoceroyl-Cer"),
    SP_1_O_CEROTOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-cerotoyl-Cer"),
    SP_1_O_CARBOCEROYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-carboceroyl-Cer"),
    SP_1_O_TRICOSANOYL_CER(LipidCategory.SP, "Acylceramides [SP0204]", 2, "2", "1-O-tricosanoyl-Cer");

    private final LipidCategory category;

    private final String lipidMapsClassName;

    private final String allowedNumFaStr;

    private final List<Integer> allowedNumFa;

    private final Integer maxNumFa;

    private final List<String> synonyms;

    private LipidClass(LipidCategory category, String lipidMapsClassName, Integer maxNumFa,
            String allowedNumFaStr, String... synonyms) {
        this.category = category;
        this.lipidMapsClassName = lipidMapsClassName;
        this.maxNumFa = maxNumFa;
        this.allowedNumFaStr = allowedNumFaStr;
        if (synonyms.length == 0) {
            throw new IllegalArgumentException("Must supply at least one synonym!");
        };
        this.allowedNumFa = Arrays.asList(allowedNumFaStr.split("\\|")).stream().map((t) -> {
            return Integer.parseInt(t);
        }).collect(java.util.stream.Collectors.toList());
        this.synonyms = Arrays.asList(synonyms);
    }

    public LipidCategory getCategory() {
        return this.category;
    }

    public String getAbbreviation() {
        return this.synonyms.get(0);
    }

    public String getLipidMapsClassName() {
        return this.lipidMapsClassName;
    }

    public Integer getMaxNumFa() {
        return this.maxNumFa;
    }

    public List<Integer> getAllowedNumFa() {
        return this.allowedNumFa;
    }

    public List<String> getSynonyms() {
        return this.synonyms;
    }

    public boolean matchesAbbreviation(String headGroup) {
        return this.synonyms.stream().anyMatch((synonym) -> {
            return synonym.equals(headGroup);
        });
    }

    public String getLysoAbbreviation(LipidClass lipidClass) {
        if (lipidClass.getCategory() == LipidCategory.GP) {
            return "L" + lipidClass.getAbbreviation();
        }
        throw new ConstraintViolationException("Lipid category must be " + LipidCategory.GP + " for lyso-classes!");
    }

    public static Optional<LipidClass> forHeadGroup(String headGroup) {
        return Arrays.asList(values()).stream().filter((lipidClass) -> {
            return lipidClass.matchesAbbreviation(headGroup.trim());
        }).findFirst();
    }
}
